---
title: "Jumeaux de naissance — 17/06"
date: "2026-06-18"
format:
  html:
    toc: true
  pdf:
    toc: true
---

# Personnalités nées le 17/06

*Données extraites de Wikidata / Wikipédia (fr) le 2026-06-18. Période : 2020–1000. Total : 840 personnalités.*

## 2021

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2020

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2019

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2018

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2017

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2016

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2015

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2014

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2013

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2012

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2011

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2010

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2009

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2008

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Emma Gunnarsen** | Norwegian singer | [Wikipedia](https://fr.wikipedia.org/wiki/Emma%20Gunnarsen) | [Q123848687](https://www.wikidata.org/wiki/Q123848687) |

## 2007

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 2006

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Joan Tincres** | French footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Joan%20Tincres) | [Q118884221](https://www.wikidata.org/wiki/Q118884221) |

## 2005

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Funa Nakayama** | Japanese skateboarder | [Wikipedia](https://fr.wikipedia.org/wiki/Funa%20Nakayama) | [Q64358909](https://www.wikidata.org/wiki/Q64358909) |
| **Noha Lemina** | Gabonese association football player (born 2005) | [Wikipedia](https://fr.wikipedia.org/wiki/Noha%20Lemina) | [Q121094976](https://www.wikidata.org/wiki/Q121094976) |

## 2004

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Solana Sierra** | Argentine tennis player | [Wikipedia](https://fr.wikipedia.org/wiki/Solana%20Sierra) | [Q111324826](https://www.wikidata.org/wiki/Q111324826) |
| **Romi Paritzki** | Israeli rhythmic gymnast | [Wikipedia](https://fr.wikipedia.org/wiki/Romi%20Paritzki) | [Q112635160](https://www.wikidata.org/wiki/Q112635160) |
| **Anton Tsarenko** | Ukrainian footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Anton%20Tsarenko) | [Q113549332](https://www.wikidata.org/wiki/Q113549332) |
| **Rofiat Imuran** | Nigerian footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Rofiat%20Imuran) | [Q117358817](https://www.wikidata.org/wiki/Q117358817) |
| **Gemma Bell** | English and Scottish rugby union player | [Wikipedia](https://fr.wikipedia.org/wiki/Gemma%20Bell) | [Q134605458](https://www.wikidata.org/wiki/Q134605458) |
| **Fuku Suzuki** | Japanese actor | [Wikipedia](https://fr.wikipedia.org/wiki/Fuku%20Suzuki) | [Q875763](https://www.wikidata.org/wiki/Q875763) |
| **Zakaria Ariss** | French-moroccan association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Zakaria%20Ariss) | [Q135844243](https://www.wikidata.org/wiki/Q135844243) |

## 2003

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Polina Fouda** | Egyptian rhythmic gymnast | [Wikipedia](https://fr.wikipedia.org/wiki/Polina%20Fouda) | [Q101208480](https://www.wikidata.org/wiki/Q101208480) |
| **Chadi Riad** | Moroccan association football player (born 2003) | [Wikipedia](https://fr.wikipedia.org/wiki/Chadi%20Riad) | [Q104784108](https://www.wikidata.org/wiki/Q104784108) |
| **Elizabeth Yeager** | American field hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/Elizabeth%20Yeager) | [Q108570201](https://www.wikidata.org/wiki/Q108570201) |
| **Tanina Mammeri** | Algerian badminton player | [Wikipedia](https://fr.wikipedia.org/wiki/Tanina%20Mammeri) | [Q109303469](https://www.wikidata.org/wiki/Q109303469) |
| **Patrycja Waszczuk** | Polish chess player | [Wikipedia](https://fr.wikipedia.org/wiki/Patrycja%20Waszczuk) | [Q83732434](https://www.wikidata.org/wiki/Q83732434) |
| **Brian Gutiérrez** | Mexican-American soccer player | [Wikipedia](https://fr.wikipedia.org/wiki/Brian%20Guti%C3%A9rrez) | [Q98536293](https://www.wikidata.org/wiki/Q98536293) |
| **Rizki Juniansyah** | Indonesian weightlifter | [Wikipedia](https://fr.wikipedia.org/wiki/Rizki%20Juniansyah) | [Q111844398](https://www.wikidata.org/wiki/Q111844398) |
| **Nazar Voloshyn** | Ukrainian footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Nazar%20Voloshyn) | [Q113585017](https://www.wikidata.org/wiki/Q113585017) |

## 2002

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Mélanie Halter** | French handball player | [Wikipedia](https://fr.wikipedia.org/wiki/M%C3%A9lanie%20Halter) | [Q136436358](https://www.wikidata.org/wiki/Q136436358) |
| **Sophie Lewis** | British cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Sophie%20Lewis) | [Q101669704](https://www.wikidata.org/wiki/Q101669704) |
| **Lee Han-beom** | South Korean footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Lee%20Han-beom) | [Q106779330](https://www.wikidata.org/wiki/Q106779330) |
| **Ryan Fosso** | Cameroonian association football player (born 2002) | [Wikipedia](https://fr.wikipedia.org/wiki/Ryan%20Fosso) | [Q113991111](https://www.wikidata.org/wiki/Q113991111) |

## 2001

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Jurriën Timber** | Dutch association football player (born 2001) | [Wikipedia](https://fr.wikipedia.org/wiki/Jurri%C3%ABn%20Timber) | [Q53952196](https://www.wikidata.org/wiki/Q53952196) |
| **Quinten Timber** | Dutch footballer (born 2001) | [Wikipedia](https://fr.wikipedia.org/wiki/Quinten%20Timber) | [Q53996595](https://www.wikidata.org/wiki/Q53996595) |
| **Lena Hentschel** | German diver | [Wikipedia](https://fr.wikipedia.org/wiki/Lena%20Hentschel) | [Q56062891](https://www.wikidata.org/wiki/Q56062891) |
| **Bledian Krasniqi** | Swiss association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Bledian%20Krasniqi) | [Q60621353](https://www.wikidata.org/wiki/Q60621353) |
| **Abdallah Sima** | Senegalese association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Abdallah%20Sima) | [Q100999415](https://www.wikidata.org/wiki/Q100999415) |
| **Narek Grigoryan** | Armenian footballer (born 2001) | [Wikipedia](https://fr.wikipedia.org/wiki/Narek%20Grigoryan) | [Q109615452](https://www.wikidata.org/wiki/Q109615452) |
| **Pauls Rubenis** | Latvian cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Pauls%20Rubenis) | [Q99141479](https://www.wikidata.org/wiki/Q99141479) |
| **Jofre Carreras** | Spanish association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Jofre%20Carreras) | [Q99675666](https://www.wikidata.org/wiki/Q99675666) |

## 2000

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Shimpei Fukuoka** | Japanese association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Shimpei%20Fukuoka) | [Q43424355](https://www.wikidata.org/wiki/Q43424355) |
| **Odessa A'zion** | American actress and voice actress | [Wikipedia](https://fr.wikipedia.org/wiki/Odessa%20A'zion) | [Q55346754](https://www.wikidata.org/wiki/Q55346754) |
| **Ghailene Khattali** | Tunisian canoeist | [Wikipedia](https://fr.wikipedia.org/wiki/Ghailene%20Khattali) | [Q70613456](https://www.wikidata.org/wiki/Q70613456) |
| **Weronika Falkowska** | Polish tennis player | [Wikipedia](https://fr.wikipedia.org/wiki/Weronika%20Falkowska) | [Q105404664](https://www.wikidata.org/wiki/Q105404664) |
| **Masai Russell** | American track and field sprinter and hurdler | [Wikipedia](https://fr.wikipedia.org/wiki/Masai%20Russell) | [Q122662304](https://www.wikidata.org/wiki/Q122662304) |
| **Thanongsak Simsri** | Thai professional boxer | [Wikipedia](https://fr.wikipedia.org/wiki/Thanongsak%20Simsri) | [Q133830099](https://www.wikidata.org/wiki/Q133830099) |

## 1999

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Henri Jokiharju** | Finnish ice hockey player (born 1999) | [Wikipedia](https://fr.wikipedia.org/wiki/Henri%20Jokiharju) | [Q24827212](https://www.wikidata.org/wiki/Q24827212) |
| **Luis Sinisterra** | Colombian association football player (born 1999) | [Wikipedia](https://fr.wikipedia.org/wiki/Luis%20Sinisterra) | [Q26838145](https://www.wikidata.org/wiki/Q26838145) |
| **Noa Lang** | Dutch association football player (born 1999) | [Wikipedia](https://fr.wikipedia.org/wiki/Noa%20Lang) | [Q29441778](https://www.wikidata.org/wiki/Q29441778) |
| **Ulrik Fredriksen** | Norwegian association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Ulrik%20Fredriksen) | [Q35497891](https://www.wikidata.org/wiki/Q35497891) |
| **Elena Rybakina** | Kazakhstani tennis player | [Wikipedia](https://fr.wikipedia.org/wiki/Elena%20Rybakina) | [Q42055714](https://www.wikidata.org/wiki/Q42055714) |
| **Immanuel Quickley** | American basketball player | [Wikipedia](https://fr.wikipedia.org/wiki/Immanuel%20Quickley) | [Q55433150](https://www.wikidata.org/wiki/Q55433150) |
| **Thibaut Collet** | French athletics competitor | [Wikipedia](https://fr.wikipedia.org/wiki/Thibaut%20Collet) | [Q65921158](https://www.wikidata.org/wiki/Q65921158) |
| **Shaquil Delos** | French professional footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Shaquil%20Delos) | [Q66809843](https://www.wikidata.org/wiki/Q66809843) |
| **Camilo Ugo Carabelli** | Argentine tennis player (born 1999) | [Wikipedia](https://fr.wikipedia.org/wiki/Camilo%20Ugo%20Carabelli) | [Q106207380](https://www.wikidata.org/wiki/Q106207380) |
| **Clara Marz** | French influencer and YouTuber | [Wikipedia](https://fr.wikipedia.org/wiki/Clara%20Marz) | [Q110940001](https://www.wikidata.org/wiki/Q110940001) |
| **Margaux Sieracki** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Margaux%20Sieracki) | [Q111027358](https://www.wikidata.org/wiki/Q111027358) |
| **Vinicius Souza** | Brazilian footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Vin%C3%ADcius%20Souza) | [Q69968896](https://www.wikidata.org/wiki/Q69968896) |
| **Josh Brook** | Canadian ice hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/Josh%20Brook) | [Q97293273](https://www.wikidata.org/wiki/Q97293273) |
| **Alijah Vera-Tucker** | American football player | [Wikipedia](https://fr.wikipedia.org/wiki/Alijah%20Vera-Tucker) | [Q99592414](https://www.wikidata.org/wiki/Q99592414) |
| **Xoliswa Khuzwayo** | South African rugby union player | [Wikipedia](https://fr.wikipedia.org/wiki/Xoliswa%20Khuzwayo) | [Q135989860](https://www.wikidata.org/wiki/Q135989860) |

## 1998

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Benjamin Källman** | Finnish association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Benjamin%20K%C3%A4llman) | [Q23869556](https://www.wikidata.org/wiki/Q23869556) |
| **Arnaud Nordin** | French association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Arnaud%20Nordin) | [Q27049316](https://www.wikidata.org/wiki/Q27049316) |
| **Joel Osikel** | Nigerian association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Joel%20Osikel) | [Q28006837](https://www.wikidata.org/wiki/Q28006837) |
| **Nujood Ali** | Advocate of opposition to forced marriages | [Wikipedia](https://fr.wikipedia.org/wiki/Nojoud%20Ali) | [Q458632](https://www.wikidata.org/wiki/Q458632) |
| **Michal Hlavatý** | Czech association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Michal%20Hlavat%C3%BD) | [Q39034506](https://www.wikidata.org/wiki/Q39034506) |
| **Zeineba Yimer** | Ethiopian long distance runner | [Wikipedia](https://fr.wikipedia.org/wiki/Zeineba%20Yimer) | [Q51885236](https://www.wikidata.org/wiki/Q51885236) |
| **Hayden Coulson** | English footballer (born 1998) | [Wikipedia](https://fr.wikipedia.org/wiki/Hayden%20Coulson) | [Q55759511](https://www.wikidata.org/wiki/Q55759511) |
| **Ankita Bhakat** | Indian archer | [Wikipedia](https://fr.wikipedia.org/wiki/Ankita%20Bhakat) | [Q56651204](https://www.wikidata.org/wiki/Q56651204) |
| **Mattia Bevilacqua** | Italian cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Mattia%20Bevilacqua) | [Q70614744](https://www.wikidata.org/wiki/Q70614744) |
| **Rinsola Babajide** | English-Nigerian footballer (born 1998) | [Wikipedia](https://fr.wikipedia.org/wiki/Rinsola%20Babajide) | [Q28864269](https://www.wikidata.org/wiki/Q28864269) |
| **Rémi Conroy** |  | [Wikipedia](https://fr.wikipedia.org/wiki/R%C3%A9mi%20Conroy) | [Q121009987](https://www.wikidata.org/wiki/Q121009987) |
| **Méline Rollin** | French long-distance runner | [Wikipedia](https://fr.wikipedia.org/wiki/M%C3%A9line%20Rollin) | [Q124623774](https://www.wikidata.org/wiki/Q124623774) |

## 1997

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Rosefline Chepng'etich** | Kenyan athletics competitor | [Wikipedia](https://fr.wikipedia.org/wiki/Roseline%20Chepngetich) | [Q20866969](https://www.wikidata.org/wiki/Q20866969) |
| **Alexander Bublik** | Kazakh tennis player | [Wikipedia](https://fr.wikipedia.org/wiki/Alexander%20Bublik) | [Q23678983](https://www.wikidata.org/wiki/Q23678983) |
| **KJ Apa** | New Zealand actor | [Wikipedia](https://fr.wikipedia.org/wiki/K.%20J.%20Apa) | [Q24186718](https://www.wikidata.org/wiki/Q24186718) |
| **Ottomar Ladva** | Estonian chess player and poker player (born 1997) | [Wikipedia](https://fr.wikipedia.org/wiki/Ottomar%20Ladva) | [Q16405443](https://www.wikidata.org/wiki/Q16405443) |
| **Harm Vanhoucke** | Belgian cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Harm%20Vanhoucke) | [Q27068073](https://www.wikidata.org/wiki/Q27068073) |
| **Michael Hernandez** | American cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Michael%20Hernandez) | [Q29454066](https://www.wikidata.org/wiki/Q29454066) |
| **Amir Coffey** | American basketball player | [Wikipedia](https://fr.wikipedia.org/wiki/Amir%20Coffey) | [Q33113645](https://www.wikidata.org/wiki/Q33113645) |
| **Malaly Dembélé** | French association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Malaly%20Demb%C3%A9l%C3%A9) | [Q37467177](https://www.wikidata.org/wiki/Q37467177) |
| **Maksim Andraloits** | Belarusian decathlete | [Wikipedia](https://fr.wikipedia.org/wiki/Maksim%20Andraloits) | [Q38719586](https://www.wikidata.org/wiki/Q38719586) |
| **Sofia Pozdniakova** | Russian fencer | [Wikipedia](https://fr.wikipedia.org/wiki/Sofia%20Pozdniakova) | [Q52767984](https://www.wikidata.org/wiki/Q52767984) |
| **Ky Bowman** | American basketball player | [Wikipedia](https://fr.wikipedia.org/wiki/Ky%20Bowman) | [Q63119820](https://www.wikidata.org/wiki/Q63119820) |
| **Dunya Abutaleb** | Saudi taekwondo athlete | [Wikipedia](https://fr.wikipedia.org/wiki/Dunya%20Abutaleb) | [Q115787118](https://www.wikidata.org/wiki/Q115787118) |
| **Emmanuel Agbadou** | Ivorian footballer (born 1997) | [Wikipedia](https://fr.wikipedia.org/wiki/Emmanuel%20Agbadou) | [Q69523791](https://www.wikidata.org/wiki/Q69523791) |
| **Jonah Radebaugh** | American-Montenegrin basketball player | [Wikipedia](https://fr.wikipedia.org/wiki/Jonah%20Radebaugh) | [Q99390713](https://www.wikidata.org/wiki/Q99390713) |

## 1996

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Matheus Ferraz** | Brazilian association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Matheus%20Ferraz) | [Q10327357](https://www.wikidata.org/wiki/Q10327357) |
| **Antonio Marín Molina** | Spanish footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Antonio%20Mar%C3%ADn%20Molina) | [Q18637694](https://www.wikidata.org/wiki/Q18637694) |
| **Ben Whiteman** | English Footballer (born 1996) | [Wikipedia](https://fr.wikipedia.org/wiki/Benjamin%20Whiteman) | [Q18638176](https://www.wikidata.org/wiki/Q18638176) |
| **Maximilian Ullmann** | Austrian association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Maximilian%20Ullmann) | [Q21000291](https://www.wikidata.org/wiki/Q21000291) |
| **Jake Bibby** | English rugby league footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Jacob%20Bibby) | [Q22087216](https://www.wikidata.org/wiki/Q22087216) |
| **Ivan Yakimushkin** | Russian cross-country skier | [Wikipedia](https://fr.wikipedia.org/wiki/Ivan%20Iakimouchkine) | [Q24955858](https://www.wikidata.org/wiki/Q24955858) |
| **Olivia Mellegård** | Swedish handball player | [Wikipedia](https://fr.wikipedia.org/wiki/Olivia%20Melleg%C3%A5rd) | [Q27469933](https://www.wikidata.org/wiki/Q27469933) |
| **Alicia Langer** | German handball player | [Wikipedia](https://fr.wikipedia.org/wiki/Alicia%20Stolle) | [Q27978725](https://www.wikidata.org/wiki/Q27978725) |
| **Maxime D'Arpino** | French footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Maxime%20D'Arpino) | [Q40164764](https://www.wikidata.org/wiki/Q40164764) |
| **Samuel Blais** | Canadian ice hockey player (born 1996) | [Wikipedia](https://fr.wikipedia.org/wiki/Samuel%20Blais) | [Q42765134](https://www.wikidata.org/wiki/Q42765134) |
| **Hippolyte Machetti** | French sailor | [Wikipedia](https://fr.wikipedia.org/wiki/Hippolyte%20Machetti) | [Q57554631](https://www.wikidata.org/wiki/Q57554631) |
| **Grâce Dorothée** | Cameroonian artist | [Wikipedia](https://fr.wikipedia.org/wiki/Gr%C3%A2ce%20Doroth%C3%A9e) | [Q117256236](https://www.wikidata.org/wiki/Q117256236) |
| **Tom Dradriga** | Ugandan middle-distance runner | [Wikipedia](https://fr.wikipedia.org/wiki/Tom%20Dradriga) | [Q121811294](https://www.wikidata.org/wiki/Q121811294) |
| **Sandi Guerra** | Panamanian sport cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Sandi%20Guerra) | [Q126414363](https://www.wikidata.org/wiki/Q126414363) |
| **Choi Sung-eun** | South Korean actress | [Wikipedia](https://fr.wikipedia.org/wiki/Choi%20Sung-eun) | [Q106634860](https://www.wikidata.org/wiki/Q106634860) |
| **Youstin Salas** | Costa Rican footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Youstin%20Salas) | [Q111837347](https://www.wikidata.org/wiki/Q111837347) |
| **Lisa Rooms** | Belgian middle-distance runner | [Wikipedia](https://fr.wikipedia.org/wiki/Lisa%20Rooms) | [Q67203990](https://www.wikidata.org/wiki/Q67203990) |
| **Yang Qian** | Chinese para table tennis player | [Wikipedia](https://fr.wikipedia.org/wiki/Yang%20Qian%20(tennis%20de%20table)) | [Q84196433](https://www.wikidata.org/wiki/Q84196433) |

## 1995

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1994

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1993

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1992

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Mujinga Kambundji** | Swiss athletics competitor | [Wikipedia](https://fr.wikipedia.org/wiki/Mujinga%20Kambundji) | [Q125707](https://www.wikidata.org/wiki/Q125707) |
| **Maxime Lestienne** | Belgian association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Maxime%20Lestienne) | [Q1362594](https://www.wikidata.org/wiki/Q1362594) |
| **Hugo Valente** | French racing driver | [Wikipedia](https://fr.wikipedia.org/wiki/Hugo%20Valente) | [Q1635804](https://www.wikidata.org/wiki/Q1635804) |
| **Victor Guerin** | Brazilian racing driver | [Wikipedia](https://fr.wikipedia.org/wiki/Victor%20Guerin%20(pilote%20automobile)) | [Q1891576](https://www.wikidata.org/wiki/Q1891576) |
| **Fredrik Ulvestad** | Norwegian footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Fredrik%20Ulvestad) | [Q2005608](https://www.wikidata.org/wiki/Q2005608) |
| **André Negrão** | Brazilian racing driver | [Wikipedia](https://fr.wikipedia.org/wiki/Andr%C3%A9%20Negr%C3%A3o) | [Q506359](https://www.wikidata.org/wiki/Q506359) |
| **Silvia Lotti** | Italian volleyball player | [Wikipedia](https://fr.wikipedia.org/wiki/Silvia%20Lotti) | [Q3484044](https://www.wikidata.org/wiki/Q3484044) |
| **Fabián Castillo** | Colombian footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Fabi%C3%A1n%20Castillo) | [Q3737896](https://www.wikidata.org/wiki/Q3737896) |
| **Josué Sá** | Portuguese footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Josu%C3%A9%20S%C3%A1) | [Q6291201](https://www.wikidata.org/wiki/Q6291201) |
| **Ryan Allsop** | English football goalkeeper (born 1992) | [Wikipedia](https://fr.wikipedia.org/wiki/Ryan%20Allsop) | [Q7383831](https://www.wikidata.org/wiki/Q7383831) |
| **Tuğrul Erat** | Turkish-Azerbaijani association football player (born 1992) | [Wikipedia](https://fr.wikipedia.org/wiki/Tu%C4%9Frul%20Erat) | [Q15363466](https://www.wikidata.org/wiki/Q15363466) |
| **Greg McKegg** | Canadian ice hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/Greg%20McKegg) | [Q15705533](https://www.wikidata.org/wiki/Q15705533) |
| **Shura** | British musician | [Wikipedia](https://fr.wikipedia.org/wiki/Shura%20(musicienne%20britannique)) | [Q19160305](https://www.wikidata.org/wiki/Q19160305) |
| **Vaea Fifita** | Tongan-New Zealand rugby union footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Vaea%20Fifita) | [Q20631055](https://www.wikidata.org/wiki/Q20631055) |
| **Sun Yiwen** | Chinese fencer | [Wikipedia](https://fr.wikipedia.org/wiki/Sun%20Yiwen) | [Q20820947](https://www.wikidata.org/wiki/Q20820947) |
| **Théo Derot** | French handball player | [Wikipedia](https://fr.wikipedia.org/wiki/Th%C3%A9o%20Derot) | [Q22093694](https://www.wikidata.org/wiki/Q22093694) |
| **Geoffrey Fabbri** | French rugby union player | [Wikipedia](https://fr.wikipedia.org/wiki/Geoffrey%20Fabbri) | [Q22909951](https://www.wikidata.org/wiki/Q22909951) |
| **Patrícia Morais** | Portuguese association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Patr%C3%ADcia%20Morais) | [Q23771632](https://www.wikidata.org/wiki/Q23771632) |
| **Keenan Horne** | South African field hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/Keenan%20Horne) | [Q107643294](https://www.wikidata.org/wiki/Q107643294) |
| **Roberto Lopes** | Irish-Cape Verdean footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Roberto%20Lopes) | [Q85797565](https://www.wikidata.org/wiki/Q85797565) |

## 1991

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Jared Goldberg** | American alpine skier | [Wikipedia](https://fr.wikipedia.org/wiki/Jared%20Goldberg) | [Q1184645](https://www.wikidata.org/wiki/Q1184645) |
| **Leandro Cabrera** | Spanish footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Leandro%20Cabrera) | [Q2299030](https://www.wikidata.org/wiki/Q2299030) |
| **Souleymane Demba** | Malian footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Souleymane%20Demba) | [Q3491649](https://www.wikidata.org/wiki/Q3491649) |
| **Robert Berić** | Slovenian footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Robert%20Beri%C4%87) | [Q3612407](https://www.wikidata.org/wiki/Q3612407) |
| **Patrick Ronaldinho Wleh** | Liberian footballer (born 1991) | [Wikipedia](https://fr.wikipedia.org/wiki/Patrick%20Wleh) | [Q951454](https://www.wikidata.org/wiki/Q951454) |
| **Laurie Dupont** | French actress | [Wikipedia](https://fr.wikipedia.org/wiki/Laurie%20Dupont) | [Q11778988](https://www.wikidata.org/wiki/Q11778988) |
| **Kayane** | French journalist and electronic sports player | [Wikipedia](https://fr.wikipedia.org/wiki/Kayane) | [Q15116764](https://www.wikidata.org/wiki/Q15116764) |
| **Daniel Tupou** | Australian rugby league footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Daniel%20Tupou) | [Q5218939](https://www.wikidata.org/wiki/Q5218939) |
| **Grégoire Defrel** | French footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Gr%C3%A9goire%20Defrel) | [Q5612770](https://www.wikidata.org/wiki/Q5612770) |
| **Lise Arricastre** | rugby union player | [Wikipedia](https://fr.wikipedia.org/wiki/Lise%20Arricastre) | [Q15973358](https://www.wikidata.org/wiki/Q15973358) |
| **Alfredo Ávila** | Mexican squash player | [Wikipedia](https://fr.wikipedia.org/wiki/Alfredo%20%C3%81vila) | [Q16146945](https://www.wikidata.org/wiki/Q16146945) |
| **Aleksandr Safonov** | Russian volleyball player | [Wikipedia](https://fr.wikipedia.org/wiki/Aleksandr%20Safonov) | [Q16382860](https://www.wikidata.org/wiki/Q16382860) |
| **Akker van der Merwe** | South African rugby union footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Akker%20van%20der%20Merwe) | [Q16762452](https://www.wikidata.org/wiki/Q16762452) |
| **Basile Vincette** | French Rink hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/Basile%20Vincette) | [Q17621797](https://www.wikidata.org/wiki/Q17621797) |
| **Shura** | British musician | [Wikipedia](https://fr.wikipedia.org/wiki/Shura%20(musicienne%20britannique)) | [Q19160305](https://www.wikidata.org/wiki/Q19160305) |
| **Amjad Al-Saboory** | Iraqi film director | [Wikipedia](https://fr.wikipedia.org/wiki/Amjad%20Alsaboory) | [Q20086606](https://www.wikidata.org/wiki/Q20086606) |
| **Nat Young** | American surfer | [Wikipedia](https://fr.wikipedia.org/wiki/Nat%20Young%20(surfeur%20am%C3%A9ricain)) | [Q20968493](https://www.wikidata.org/wiki/Q20968493) |
| **Òscar Cabanas** | Andorran cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/%C3%92scar%20Cabanas) | [Q28872368](https://www.wikidata.org/wiki/Q28872368) |
| **Zahraa Ghandour** | Iraqi actress | [Wikipedia](https://fr.wikipedia.org/wiki/Zahraa%20Ghandour) | [Q55080934](https://www.wikidata.org/wiki/Q55080934) |

## 1990

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Hansle Parchment** | Jamaican track and field athlete | [Wikipedia](https://fr.wikipedia.org/wiki/Hansle%20Parchment) | [Q1687](https://www.wikidata.org/wiki/Q1687) |
| **Alan Dzagoev** | Russian association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Alan%20Dzago%C3%AFev) | [Q20469](https://www.wikidata.org/wiki/Q20469) |
| **Jordan Henderson** | English association football player (born 1990) | [Wikipedia](https://fr.wikipedia.org/wiki/Jordan%20Henderson) | [Q273715](https://www.wikidata.org/wiki/Q273715) |
| **Ferry Doedens** | Dutch actor | [Wikipedia](https://fr.wikipedia.org/wiki/Ferry%20Doedens) | [Q457443](https://www.wikidata.org/wiki/Q457443) |
| **Georg Preidler** | Austrian cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Georg%20Preidler) | [Q517775](https://www.wikidata.org/wiki/Q517775) |
| **Bogdan Juratoni** | Romanian boxer | [Wikipedia](https://fr.wikipedia.org/wiki/Bogdan%20Juratoni) | [Q2030409](https://www.wikidata.org/wiki/Q2030409) |
| **Justin Bethel** | American football player, defensive back, cornerback, special teamer | [Wikipedia](https://fr.wikipedia.org/wiki/Justin%20Bethel) | [Q3811565](https://www.wikidata.org/wiki/Q3811565) |
| **Joel Robles** | Spanish association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Joel%20Robles) | [Q547296](https://www.wikidata.org/wiki/Q547296) |
| **Andrew Chafin** | American baseball player | [Wikipedia](https://fr.wikipedia.org/wiki/Andrew%20Chafin) | [Q16233049](https://www.wikidata.org/wiki/Q16233049) |
| **Josh Mansour** | Australian rugby league footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Josh%20Mansour) | [Q6289144](https://www.wikidata.org/wiki/Q6289144) |
| **Kevin Molino** | Trinidad and Tobago footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Kevin%20Molino) | [Q6397020](https://www.wikidata.org/wiki/Q6397020) |
| **Louise Quinn** | Irish association footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Louise%20Quinn) | [Q6688920](https://www.wikidata.org/wiki/Q6688920) |
| **Matt Barnes** | baseball player | [Wikipedia](https://fr.wikipedia.org/wiki/Matt%20Barnes%20(baseball)) | [Q6788312](https://www.wikidata.org/wiki/Q6788312) |
| **Louise Smyth** | South African swimmer | [Wikipedia](https://fr.wikipedia.org/wiki/Louise%20Smyth) | [Q109366506](https://www.wikidata.org/wiki/Q109366506) |
| **Laura Wright** | English soprano | [Wikipedia](https://fr.wikipedia.org/wiki/Laura%20Wright) | [Q16233665](https://www.wikidata.org/wiki/Q16233665) |
| **Mehdi Ouertani** | Tunisian association football player (1990-) | [Wikipedia](https://fr.wikipedia.org/wiki/Mehdi%20Ouertani) | [Q16663990](https://www.wikidata.org/wiki/Q16663990) |
| **Monica Barbaro** | American actress | [Wikipedia](https://fr.wikipedia.org/wiki/Monica%20Barbaro) | [Q26703036](https://www.wikidata.org/wiki/Q26703036) |

## 1989

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Harun Tekin** | Turkish association football player (born 1989) | [Wikipedia](https://fr.wikipedia.org/wiki/Harun%20Tekin%20(football)) | [Q1587824](https://www.wikidata.org/wiki/Q1587824) |
| **Vladimir Lučić** | Serbian basketball player | [Wikipedia](https://fr.wikipedia.org/wiki/Vladimir%20Lu%C4%8Di%C4%87) | [Q2054671](https://www.wikidata.org/wiki/Q2054671) |
| **Queralt Castellet** | Spanish snowboarder | [Wikipedia](https://fr.wikipedia.org/wiki/Queralt%20Castellet) | [Q262724](https://www.wikidata.org/wiki/Q262724) |
| **Serikzhan Muzhikov** | Kazakhstani footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Serikzhan%20Muzhikov) | [Q275833](https://www.wikidata.org/wiki/Q275833) |
| **Vitalijs Pavlovs** | Latvian ice hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/Vit%C4%81lijs%20Pavlovs) | [Q376952](https://www.wikidata.org/wiki/Q376952) |
| **Tanja Schärer** | Swiss freestyle skier | [Wikipedia](https://fr.wikipedia.org/wiki/Tanja%20Sch%C3%A4rer) | [Q2392755](https://www.wikidata.org/wiki/Q2392755) |
| **Mirka Andolfo** | Italian comics artist | [Wikipedia](https://fr.wikipedia.org/wiki/Mirka%20Andolfo) | [Q3858846](https://www.wikidata.org/wiki/Q3858846) |
| **Jordan Patrick Smith** | Scottish-Australian actor | [Wikipedia](https://fr.wikipedia.org/wiki/Jordan%20Patrick%20Smith) | [Q5934204](https://www.wikidata.org/wiki/Q5934204) |
| **Nanna Christiansen** | Danish footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Nanna%20Christiansen) | [Q6963799](https://www.wikidata.org/wiki/Q6963799) |
| **Graham Vigrass** | Canadian volleyball player | [Wikipedia](https://fr.wikipedia.org/wiki/Graham%20Vigrass) | [Q21097125](https://www.wikidata.org/wiki/Q21097125) |
| **Nicolas Kraska** | rugby union player (1989-) | [Wikipedia](https://fr.wikipedia.org/wiki/Nicolas%20Kraska) | [Q47581016](https://www.wikidata.org/wiki/Q47581016) |
| **Simone Battle** | American singer and dancer (1989–2014) | [Wikipedia](https://fr.wikipedia.org/wiki/Simone%20Battle%20(chanteuse)) | [Q7520260](https://www.wikidata.org/wiki/Q7520260) |

## 1988

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Stephanie Rice** | Australian swimmer | [Wikipedia](https://fr.wikipedia.org/wiki/Stephanie%20Rice) | [Q228660](https://www.wikidata.org/wiki/Q228660) |
| **Yannick Dias Pupo** | Brazilian footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Yannick%20Pupo) | [Q346147](https://www.wikidata.org/wiki/Q346147) |
| **Rodney Wallace** | Costa Rican footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Rodney%20Wallace) | [Q514594](https://www.wikidata.org/wiki/Q514594) |
| **Demba Savage** | Gambian footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Demba%20Savage) | [Q981036](https://www.wikidata.org/wiki/Q981036) |
| **Sam Baird** | English snooker player | [Wikipedia](https://fr.wikipedia.org/wiki/Sam%20Baird) | [Q1309104](https://www.wikidata.org/wiki/Q1309104) |
| **Marek Čanecký** | Slovak bicycle racer | [Wikipedia](https://fr.wikipedia.org/wiki/Marek%20%C4%8Caneck%C3%BD) | [Q1687750](https://www.wikidata.org/wiki/Q1687750) |
| **Shaun MacDonald** | Welsh footballer (born 1988) | [Wikipedia](https://fr.wikipedia.org/wiki/Shaun%20MacDonald) | [Q1996125](https://www.wikidata.org/wiki/Q1996125) |
| **Vitaliy Kilchytskyy** | Ukrainian biathlete | [Wikipedia](https://fr.wikipedia.org/wiki/Vitaliy%20Kilchytskyy) | [Q2586443](https://www.wikidata.org/wiki/Q2586443) |
| **Mark Payne** | American professional basketball player | [Wikipedia](https://fr.wikipedia.org/wiki/Mark%20Payne) | [Q3849533](https://www.wikidata.org/wiki/Q3849533) |
| **Amiran Papinashvili** | Georgian judoka | [Wikipedia](https://fr.wikipedia.org/wiki/Amiran%20Papinashvili) | [Q15643942](https://www.wikidata.org/wiki/Q15643942) |
| **Aline Frazão** | Angolan singer-songwriter | [Wikipedia](https://fr.wikipedia.org/wiki/Aline%20Fraz%C3%A3o) | [Q16336392](https://www.wikidata.org/wiki/Q16336392) |
| **Hugo Seco** | Portuguese footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Hugo%20Seco) | [Q19364996](https://www.wikidata.org/wiki/Q19364996) |
| **Héctor Catalá Laparra** | Spanish triathlete | [Wikipedia](https://fr.wikipedia.org/wiki/H%C3%A9ctor%20Catal%C3%A1%20Laparra) | [Q108301816](https://www.wikidata.org/wiki/Q108301816) |
| **Romain Mader** | Swiss photographer | [Wikipedia](https://fr.wikipedia.org/wiki/Romain%20Mader) | [Q114759076](https://www.wikidata.org/wiki/Q114759076) |
| **Sarah Edwards** | British politician (born 1988) | [Wikipedia](https://fr.wikipedia.org/wiki/Sarah%20Edwards) | [Q123113780](https://www.wikidata.org/wiki/Q123113780) |
| **Melanie Maurer** | Swiss cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Melanie%20Maurer) | [Q52784502](https://www.wikidata.org/wiki/Q52784502) |

## 1987

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1986

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1985

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1984

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1983

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1982

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1981

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1980

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1979

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1978

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1977

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1976

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1975

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1974

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1973

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1972

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **C. H. Greenblatt** | American animator | [Wikipedia](https://fr.wikipedia.org/wiki/C.%20H.%20Greenblatt) | [Q1022489](https://www.wikidata.org/wiki/Q1022489) |
| **Iztok Čop** | Slovenian rower | [Wikipedia](https://fr.wikipedia.org/wiki/Iztok%20%C4%8Cop) | [Q1230878](https://www.wikidata.org/wiki/Q1230878) |
| **Zafar Guliyev** | Olympic wrestler | [Wikipedia](https://fr.wikipedia.org/wiki/Zafar%20Guliyev) | [Q1393610](https://www.wikidata.org/wiki/Q1393610) |
| **Antoine Albeau** | French windsurfer | [Wikipedia](https://fr.wikipedia.org/wiki/Antoine%20Albeau) | [Q585587](https://www.wikidata.org/wiki/Q585587) |
| **Fabrice Bellard** | French computer programmer | [Wikipedia](https://fr.wikipedia.org/wiki/Fabrice%20Bellard) | [Q93013](https://www.wikidata.org/wiki/Q93013) |
| **Roman Meluzín** | Czech ice hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/Roman%20Meluz%C3%ADn) | [Q954055](https://www.wikidata.org/wiki/Q954055) |
| **Dan Burincă** | gymnast | [Wikipedia](https://fr.wikipedia.org/wiki/Dan%20Burinc%C4%83) | [Q963696](https://www.wikidata.org/wiki/Q963696) |
| **Michał Żebrowski** | Polish actor | [Wikipedia](https://fr.wikipedia.org/wiki/Micha%C5%82%20%C5%BBebrowski) | [Q1930601](https://www.wikidata.org/wiki/Q1930601) |
| **Bjørn Tore Kvarme** | Norwegian association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Bj%C3%B8rn%20Tore%20Kvarme) | [Q2288840](https://www.wikidata.org/wiki/Q2288840) |
| **Natalia Boa Vista** | fictional character on American television series CSI: Miami | [Wikipedia](https://fr.wikipedia.org/wiki/Natalia%20Boa%20Vista) | [Q2690862](https://www.wikidata.org/wiki/Q2690862) |
| **Daniel Effiong** | Nigerian sprinter | [Wikipedia](https://fr.wikipedia.org/wiki/Daniel%20Effiong) | [Q3014005](https://www.wikidata.org/wiki/Q3014005) |
| **Steven Fletcher** | Canadian politician | [Wikipedia](https://fr.wikipedia.org/wiki/Steven%20Fletcher%20(homme%20politique)) | [Q3499223](https://www.wikidata.org/wiki/Q3499223) |
| **Simon Evans** | Australian rally driver | [Wikipedia](https://fr.wikipedia.org/wiki/Simon%20Evans) | [Q16040243](https://www.wikidata.org/wiki/Q16040243) |
| **Mario Delgado** | Mexican politician | [Wikipedia](https://fr.wikipedia.org/wiki/Mario%20Delgado%20Carrillo) | [Q5998612](https://www.wikidata.org/wiki/Q5998612) |
| **Cristina Ayala Santamaría** | Spanish politician | [Wikipedia](https://fr.wikipedia.org/wiki/Cristina%20Ayala%20Santamar%C3%ADa) | [Q28872635](https://www.wikidata.org/wiki/Q28872635) |
| **Jean-Pierre Gagick** | French journalist | [Wikipedia](https://fr.wikipedia.org/wiki/Jean-Pierre%20Gagick) | [Q57986398](https://www.wikidata.org/wiki/Q57986398) |
| **Elijah Ary** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Elijah%20Ary) | [Q64759757](https://www.wikidata.org/wiki/Q64759757) |

## 1971

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1970

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Will Forte** | American actor, comedian, writer (born 1970) | [Wikipedia](https://fr.wikipedia.org/wiki/Will%20Forte) | [Q1319744](https://www.wikidata.org/wiki/Q1319744) |
| **Popeye Jones** | American basketball player | [Wikipedia](https://fr.wikipedia.org/wiki/Popeye%20Jones) | [Q1458255](https://www.wikidata.org/wiki/Q1458255) |
| **Jason Hanson** | American football player (born 1970) | [Wikipedia](https://fr.wikipedia.org/wiki/Jason%20Hanson) | [Q1658209](https://www.wikidata.org/wiki/Q1658209) |
| **Saïdou Sanfo** | Burkinabe cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Sa%C3%AFdou%20Sanfo) | [Q1668582](https://www.wikidata.org/wiki/Q1668582) |
| **Stéphane Fiset** | Canadian ice hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/St%C3%A9phane%20Fiset) | [Q1803738](https://www.wikidata.org/wiki/Q1803738) |
| **Michael Showalter** | American comedian | [Wikipedia](https://fr.wikipedia.org/wiki/Michael%20Showalter) | [Q2092899](https://www.wikidata.org/wiki/Q2092899) |
| **Sasha Sokol** | Mexican singer, composer, actress and television presenter | [Wikipedia](https://fr.wikipedia.org/wiki/Sasha%20Sokol) | [Q3142854](https://www.wikidata.org/wiki/Q3142854) |
| **Liudmila Garajànskaia** | Belarusian cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Ludmilla%20Gorojanskaja) | [Q11763416](https://www.wikidata.org/wiki/Q11763416) |
| **Kamel Daoud** | Algerian writer | [Wikipedia](https://fr.wikipedia.org/wiki/Kamel%20Daoud%20(%C3%A9crivain)) | [Q3192364](https://www.wikidata.org/wiki/Q3192364) |
| **Anders Ygeman** | Swedish politician | [Wikipedia](https://fr.wikipedia.org/wiki/Anders%20Ygeman) | [Q3375050](https://www.wikidata.org/wiki/Q3375050) |
| **Ivy Taylor** | Former mayor of San Antonio, Texas | [Wikipedia](https://fr.wikipedia.org/wiki/Ivy%20Taylor) | [Q17721870](https://www.wikidata.org/wiki/Q17721870) |
| **Gerald Knaus** | Austrian sociologist | [Wikipedia](https://fr.wikipedia.org/wiki/Gerald%20Knaus) | [Q65966910](https://www.wikidata.org/wiki/Q65966910) |

## 1969

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Paul Tergat** | Kenyan long-distance runner (born 1969) | [Wikipedia](https://fr.wikipedia.org/wiki/Paul%20Tergat) | [Q313799](https://www.wikidata.org/wiki/Q313799) |
| **Susan Williams** | United States triathlete, born 1969. | [Wikipedia](https://fr.wikipedia.org/wiki/Susan%20Williams) | [Q439150](https://www.wikidata.org/wiki/Q439150) |
| **Ilya Tsymbalar** | Russian footballer (1969-2013) | [Wikipedia](https://fr.wikipedia.org/wiki/Ilya%20Tsymbalar) | [Q551609](https://www.wikidata.org/wiki/Q551609) |
| **Roberto Laiseka** | Spanish racing cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Roberto%20Laiseka) | [Q728352](https://www.wikidata.org/wiki/Q728352) |
| **Christer Wallin** | Swedish swimmer | [Wikipedia](https://fr.wikipedia.org/wiki/Christer%20Wallin) | [Q949721](https://www.wikidata.org/wiki/Q949721) |
| **Luis Javier González** | Spanish middle-distance runner | [Wikipedia](https://fr.wikipedia.org/wiki/Luis%20Javier%20Gonz%C3%A1lez) | [Q1251633](https://www.wikidata.org/wiki/Q1251633) |
| **Patric Kjellberg** | Swedish ice hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/Patric%20Kjellberg) | [Q1399858](https://www.wikidata.org/wiki/Q1399858) |
| **Donata Jancewicz** | Polish high jumper | [Wikipedia](https://fr.wikipedia.org/wiki/Donata%20Jancewicz) | [Q3036204](https://www.wikidata.org/wiki/Q3036204) |
| **Anna Serra Salamé** | Spanish triathlete | [Wikipedia](https://fr.wikipedia.org/wiki/Anna%20Serra) | [Q4767468](https://www.wikidata.org/wiki/Q4767468) |
| **Brecht Vermeulen** | Belgian politician | [Wikipedia](https://fr.wikipedia.org/wiki/Brecht%20Vermeulen) | [Q17048132](https://www.wikidata.org/wiki/Q17048132) |
| **Lajos Oláh** | Hungarian politician | [Wikipedia](https://fr.wikipedia.org/wiki/Lajos%20Ol%C3%A1h) | [Q31092525](https://www.wikidata.org/wiki/Q31092525) |
| **Nira Chamberlain** | British Mathematician | [Wikipedia](https://fr.wikipedia.org/wiki/Nira%20Chamberlain) | [Q45914220](https://www.wikidata.org/wiki/Q45914220) |
| **Karen Nystrom** | ice hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/Karen%20Nystrom) | [Q6369920](https://www.wikidata.org/wiki/Q6369920) |
| **Tracey Gaudry** | Australian cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Tracey%20Gaudry) | [Q7831226](https://www.wikidata.org/wiki/Q7831226) |
| **Emmanuel Chiva** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/Emmanuel%20Chiva) | [Q111208812](https://www.wikidata.org/wiki/Q111208812) |
| **Christophe Fréroux** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Christophe%20Fr%C3%A9roux) | [Q85852965](https://www.wikidata.org/wiki/Q85852965) |

## 1968

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Luka Pavicevic** | Serbian basketball coach | [Wikipedia](https://fr.wikipedia.org/wiki/Luka%20Pavi%C4%87evi%C4%87) | [Q1394167](https://www.wikidata.org/wiki/Q1394167) |
| **Minoru Suzuki** | Japanese professional wrestler and mixed martial artist | [Wikipedia](https://fr.wikipedia.org/wiki/Minoru%20Suzuki) | [Q1705122](https://www.wikidata.org/wiki/Q1705122) |
| **Bård Jørgen Elden** | Norwegian Nordic combined skier | [Wikipedia](https://fr.wikipedia.org/wiki/B%C3%A5rd%20J%C3%B8rgen%20Elden) | [Q180257](https://www.wikidata.org/wiki/Q180257) |
| **Luis Barbat** | Uruguayan footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Luis%20Barbat) | [Q1876368](https://www.wikidata.org/wiki/Q1876368) |
| **Kazuma Kiryu** | protagonist in the video game series Yakuza | [Wikipedia](https://fr.wikipedia.org/wiki/Kazuma%20Kiryu) | [Q2503497](https://www.wikidata.org/wiki/Q2503497) |
| **Charly Lownoise** | Dutch disc jockey | [Wikipedia](https://fr.wikipedia.org/wiki/Charly%20Lownoise) | [Q778133](https://www.wikidata.org/wiki/Q778133) |
| **Nicolas Sansu** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/Nicolas%20Sansu) | [Q2506441](https://www.wikidata.org/wiki/Q2506441) |
| **Daniel Levy** | Israeli diplomat and political scientist | [Wikipedia](https://fr.wikipedia.org/wiki/Daniel%20Levy%20(diplomate)) | [Q3014345](https://www.wikidata.org/wiki/Q3014345) |
| **Isabelle Larouche** | Canadian writer | [Wikipedia](https://fr.wikipedia.org/wiki/Isabelle%20Larouche) | [Q3154959](https://www.wikidata.org/wiki/Q3154959) |
| **Jean-Marc Dreyfus** | French historian | [Wikipedia](https://fr.wikipedia.org/wiki/Jean-Marc%20Dreyfus) | [Q3167369](https://www.wikidata.org/wiki/Q3167369) |
| **Deanna Raybourn** | American writer | [Wikipedia](https://fr.wikipedia.org/wiki/Deanna%20Raybourn) | [Q5246761](https://www.wikidata.org/wiki/Q5246761) |
| **Rasmus Helveg Petersen** | Danish politician | [Wikipedia](https://fr.wikipedia.org/wiki/Rasmus%20Helveg%20Petersen) | [Q12332907](https://www.wikidata.org/wiki/Q12332907) |
| **Pete D'Alessandro** | American sports executive | [Wikipedia](https://fr.wikipedia.org/wiki/Pete%20D'Alessandro) | [Q14556968](https://www.wikidata.org/wiki/Q14556968) |
| **Jo Dalton** | French rapper | [Wikipedia](https://fr.wikipedia.org/wiki/Jo%20Dalton) | [Q18744698](https://www.wikidata.org/wiki/Q18744698) |
| **Évariste Ndayishimiye** | president of Burundi | [Wikipedia](https://fr.wikipedia.org/wiki/%C3%89variste%20Ndayishimiye) | [Q27329764](https://www.wikidata.org/wiki/Q27329764) |
| **Slaviša Koprivica** | Serbian basketball player | [Wikipedia](https://fr.wikipedia.org/wiki/Slavi%C5%A1a%20Koprivica) | [Q7539404](https://www.wikidata.org/wiki/Q7539404) |

## 1967

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Eric Stefani** | musician | [Wikipedia](https://fr.wikipedia.org/wiki/Eric%20Stefani) | [Q1351671](https://www.wikidata.org/wiki/Q1351671) |
| **Barbara Sadleder** | Austrian alpine skier | [Wikipedia](https://fr.wikipedia.org/wiki/Barbara%20Sadleder) | [Q162510](https://www.wikidata.org/wiki/Q162510) |
| **Zinho** | Brazilian association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Zinho) | [Q204555](https://www.wikidata.org/wiki/Q204555) |
| **Tori Welles** | American pornographic actress and director | [Wikipedia](https://fr.wikipedia.org/wiki/Tori%20Welles) | [Q452425](https://www.wikidata.org/wiki/Q452425) |
| **Dorothea Röschmann** | German soprano singer | [Wikipedia](https://fr.wikipedia.org/wiki/Dorothea%20R%C3%B6schmann) | [Q69173](https://www.wikidata.org/wiki/Q69173) |
| **Terry Norris** | American boxer | [Wikipedia](https://fr.wikipedia.org/wiki/Terry%20Norris) | [Q2004305](https://www.wikidata.org/wiki/Q2004305) |
| **Jean-François Chabas** | French writer | [Wikipedia](https://fr.wikipedia.org/wiki/Jean-Fran%C3%A7ois%20Chabas) | [Q3165520](https://www.wikidata.org/wiki/Q3165520) |
| **Nourman Issa** | Arab-Israeli actor of Palestinian Christian descent | [Wikipedia](https://fr.wikipedia.org/wiki/Norman%20Issa) | [Q3343792](https://www.wikidata.org/wiki/Q3343792) |
| **Mikhail Krichman** | Russian cinematographer | [Wikipedia](https://fr.wikipedia.org/wiki/Mikha%C3%AFl%20Kritchman) | [Q4241424](https://www.wikidata.org/wiki/Q4241424) |
| **Alex Azar** | American politician | [Wikipedia](https://fr.wikipedia.org/wiki/Alex%20Azar) | [Q4716651](https://www.wikidata.org/wiki/Q4716651) |
| **Marianne Vlasveld** | Dutch cross-country skier and triathlonist | [Wikipedia](https://fr.wikipedia.org/wiki/Marianne%20Vlasveld) | [Q12146503](https://www.wikidata.org/wiki/Q12146503) |
| **Uwe Preißler** | East German cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Uwe%20Prei%C3%9Fler) | [Q20101540](https://www.wikidata.org/wiki/Q20101540) |
| **Jozef Síkela** | Czech politician, European Commissioner for International Partnership | [Wikipedia](https://fr.wikipedia.org/wiki/Jozef%20S%C3%ADkela) | [Q109802768](https://www.wikidata.org/wiki/Q109802768) |
| **Laurent Lairy** | French businessman | [Wikipedia](https://fr.wikipedia.org/wiki/Laurent%20Lairy) | [Q118394370](https://www.wikidata.org/wiki/Q118394370) |

## 1966

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Cédric Kahn** | French film director | [Wikipedia](https://fr.wikipedia.org/wiki/C%C3%A9dric%20Kahn) | [Q1150229](https://www.wikidata.org/wiki/Q1150229) |
| **Christy Canyon** | American pornographic actress | [Wikipedia](https://fr.wikipedia.org/wiki/Christy%20Canyon) | [Q256730](https://www.wikidata.org/wiki/Q256730) |
| **Jason Patric** | American actor | [Wikipedia](https://fr.wikipedia.org/wiki/Jason%20Patric) | [Q361412](https://www.wikidata.org/wiki/Q361412) |
| **Pablo Antón Marín Estrada** | Spanish writer | [Wikipedia](https://fr.wikipedia.org/wiki/Pablo%20Ant%C3%B3n%20Mar%C3%ADn%20Estrada) | [Q431834](https://www.wikidata.org/wiki/Q431834) |
| **Zakaria Alaoui** | Moroccan footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Zakaria%20Alaoui%20el-Achraf) | [Q2395452](https://www.wikidata.org/wiki/Q2395452) |
| **Diane Modahl** | English middle-distance runner | [Wikipedia](https://fr.wikipedia.org/wiki/Diane%20Modahl) | [Q5271533](https://www.wikidata.org/wiki/Q5271533) |

## 1965

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Dan Jansen** | American speed skater | [Wikipedia](https://fr.wikipedia.org/wiki/Dan%20Jansen) | [Q1159087](https://www.wikidata.org/wiki/Q1159087) |
| **Dana Eskelson** | American actress | [Wikipedia](https://fr.wikipedia.org/wiki/Dana%20Eskelson) | [Q1159213](https://www.wikidata.org/wiki/Q1159213) |
| **Ralf Lübke** | German sprinter | [Wikipedia](https://fr.wikipedia.org/wiki/Ralf%20L%C3%BCbke) | [Q222183](https://www.wikidata.org/wiki/Q222183) |
| **Linda Medalen** | association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Linda%20Medalen) | [Q289097](https://www.wikidata.org/wiki/Q289097) |
| **Dermontti Dawson** | American football player | [Wikipedia](https://fr.wikipedia.org/wiki/Dermontti%20Dawson) | [Q522199](https://www.wikidata.org/wiki/Q522199) |
| **Kami Cotler** | American actress | [Wikipedia](https://fr.wikipedia.org/wiki/Kami%20Cotler) | [Q525401](https://www.wikidata.org/wiki/Q525401) |
| **Gianluca Pozzi** | Italian tennis player | [Wikipedia](https://fr.wikipedia.org/wiki/Gianluca%20Pozzi) | [Q959217](https://www.wikidata.org/wiki/Q959217) |
| **José Oscar Herrera** | Uruguayan footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Jos%C3%A9%20Oscar%20Herrera) | [Q1844414](https://www.wikidata.org/wiki/Q1844414) |
| **Arabian Prince** | American rapper, singer and record producer | [Wikipedia](https://fr.wikipedia.org/wiki/Arabian%20Prince) | [Q2256420](https://www.wikidata.org/wiki/Q2256420) |
| **Toshihiro Nagoshi** | Japanese video game designer | [Wikipedia](https://fr.wikipedia.org/wiki/Toshihiro%20Nagoshi) | [Q2572612](https://www.wikidata.org/wiki/Q2572612) |
| **Pierre Bonhôte** | Swiss politician (1965-2016) | [Wikipedia](https://fr.wikipedia.org/wiki/Pierre%20Bonh%C3%B4te) | [Q3384068](https://www.wikidata.org/wiki/Q3384068) |
| **Davide Toffolo** | Comic book writer | [Wikipedia](https://fr.wikipedia.org/wiki/Davide%20Toffolo) | [Q3703633](https://www.wikidata.org/wiki/Q3703633) |
| **Brice Pauset** | French musician and composer | [Wikipedia](https://fr.wikipedia.org/wiki/Brice%20Pauset) | [Q4368843](https://www.wikidata.org/wiki/Q4368843) |
| **Danny McManus** | American football player | [Wikipedia](https://fr.wikipedia.org/wiki/Danny%20McManus) | [Q5220617](https://www.wikidata.org/wiki/Q5220617) |
| **Peter Hric** | Slovak cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Peter%20Hric) | [Q11815868](https://www.wikidata.org/wiki/Q11815868) |
| **Amidou Dossou** | Beninese carver, born 1965 | [Wikipedia](https://fr.wikipedia.org/wiki/Amidou%20Dossou) | [Q16526443](https://www.wikidata.org/wiki/Q16526443) |
| **Didier Jannel** | cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Didier%20Jannel) | [Q16628761](https://www.wikidata.org/wiki/Q16628761) |
| **Ivan Franěk** | Czech actor | [Wikipedia](https://fr.wikipedia.org/wiki/Ivan%20Fran%C4%9Bk) | [Q6096246](https://www.wikidata.org/wiki/Q6096246) |
| **Takuya Mitsuda** | Japanese manga artist | [Wikipedia](https://fr.wikipedia.org/wiki/Takuya%20Mitsuda) | [Q7678636](https://www.wikidata.org/wiki/Q7678636) |
| **Sparky D** | American hip-hop musician and rapper | [Wikipedia](https://fr.wikipedia.org/wiki/Sparky%20D) | [Q51288104](https://www.wikidata.org/wiki/Q51288104) |

## 1964

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Ricardo Moniz** | Dutch association football player and manager | [Wikipedia](https://fr.wikipedia.org/wiki/Ricardo%20Moniz) | [Q264409](https://www.wikidata.org/wiki/Q264409) |
| **Svetla Mitkova-Sınırtaş** | Turkish athlete (born 1964) | [Wikipedia](https://fr.wikipedia.org/wiki/Svetla%20Mitkova-S%C4%B1n%C4%B1rta%C5%9F) | [Q441576](https://www.wikidata.org/wiki/Q441576) |
| **Julie Baumann** | Canadian-Swiss hurdler | [Wikipedia](https://fr.wikipedia.org/wiki/Julie%20Baumann) | [Q469883](https://www.wikidata.org/wiki/Q469883) |
| **Michael Gross** | West German swimmer, Olympic gold medallist, world champion, former world record-holder | [Wikipedia](https://fr.wikipedia.org/wiki/Michael%20Gro%C3%9F) | [Q57404](https://www.wikidata.org/wiki/Q57404) |
| **Dirk Raudies** | German motorcycle racer | [Wikipedia](https://fr.wikipedia.org/wiki/Dirk%20Raudies) | [Q62561](https://www.wikidata.org/wiki/Q62561) |
| **Diane Murphy** | American actress | [Wikipedia](https://fr.wikipedia.org/wiki/Diane%20Murphy) | [Q1455013](https://www.wikidata.org/wiki/Q1455013) |
| **Erin Murphy** | American actress | [Wikipedia](https://fr.wikipedia.org/wiki/Erin%20Murphy) | [Q2323995](https://www.wikidata.org/wiki/Q2323995) |
| **Ann-Gisel Glass** | French actress | [Wikipedia](https://fr.wikipedia.org/wiki/Ann-Gisel%20Glass) | [Q2850377](https://www.wikidata.org/wiki/Q2850377) |
| **Chuck Klein** | American animator | [Wikipedia](https://fr.wikipedia.org/wiki/Chuck%20Klein) | [Q2967598](https://www.wikidata.org/wiki/Q2967598) |
| **Paolo Calabresi** | Italian actor | [Wikipedia](https://fr.wikipedia.org/wiki/Paolo%20Calabresi) | [Q3893835](https://www.wikidata.org/wiki/Q3893835) |
| **Ivan Franěk** | Czech actor | [Wikipedia](https://fr.wikipedia.org/wiki/Ivan%20Fran%C4%9Bk) | [Q6096246](https://www.wikidata.org/wiki/Q6096246) |
| **Rinaldo Capello** | Italian racing driver | [Wikipedia](https://fr.wikipedia.org/wiki/Rinaldo%20Capello) | [Q674902](https://www.wikidata.org/wiki/Q674902) |
| **Vladimír Bukač** | Czech violist | [Wikipedia](https://fr.wikipedia.org/wiki/Vladim%C3%ADr%20Buka%C4%8D) | [Q15057756](https://www.wikidata.org/wiki/Q15057756) |
| **Vanessa Beeley** | blogger, writer and photographer, propagandist, plot theorist | [Wikipedia](https://fr.wikipedia.org/wiki/Vanessa%20Beeley) | [Q47395103](https://www.wikidata.org/wiki/Q47395103) |

## 1963

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Shin Joon-sup** | South Korean boxer | [Wikipedia](https://fr.wikipedia.org/wiki/Shin%20Joon-sup) | [Q171306](https://www.wikidata.org/wiki/Q171306) |
| **Greg Kinnear** | American actor | [Wikipedia](https://fr.wikipedia.org/wiki/Greg%20Kinnear) | [Q269869](https://www.wikidata.org/wiki/Q269869) |
| **Christophe Barratier** | French film producer and director | [Wikipedia](https://fr.wikipedia.org/wiki/Christophe%20Barratier) | [Q642942](https://www.wikidata.org/wiki/Q642942) |
| **Aleksey Vdovin** | Russian water polo player (1963–2022) | [Wikipedia](https://fr.wikipedia.org/wiki/Alekse%C3%AF%20Vdovine) | [Q3609605](https://www.wikidata.org/wiki/Q3609605) |
| **Temir Sariyev** | Kyrgyzstani politician | [Wikipedia](https://fr.wikipedia.org/wiki/Temir%20Sar%C3%AFev) | [Q3736573](https://www.wikidata.org/wiki/Q3736573) |
| **June Croft** | British swimmer, Olympic silver medallist | [Wikipedia](https://fr.wikipedia.org/wiki/June%20Croft) | [Q3811250](https://www.wikidata.org/wiki/Q3811250) |
| **Sheila Broflovski** | fictional character from South Park | [Wikipedia](https://fr.wikipedia.org/wiki/Sheila%20Broflovski) | [Q4522426](https://www.wikidata.org/wiki/Q4522426) |
| **Daniel Écija** | Spanish producer and director | [Wikipedia](https://fr.wikipedia.org/wiki/Daniel%20%C3%89cija) | [Q5798797](https://www.wikidata.org/wiki/Q5798797) |
| **Paolo Rondelli** | Sanmarinese politician | [Wikipedia](https://fr.wikipedia.org/wiki/Paolo%20Rondelli) | [Q7132238](https://www.wikidata.org/wiki/Q7132238) |
| **Jean-Marc Micas** | French religious priest and Roman Catholic bishop of Tarbes and Lourdes | [Wikipedia](https://fr.wikipedia.org/wiki/Jean-Marc%20Micas) | [Q106413654](https://www.wikidata.org/wiki/Q106413654) |
| **Enzo Scarano** | Venezuelan politician | [Wikipedia](https://fr.wikipedia.org/wiki/Enzo%20Scarano) | [Q15971726](https://www.wikidata.org/wiki/Q15971726) |
| **Mikaele Kulimoetoke** | politician | [Wikipedia](https://fr.wikipedia.org/wiki/Mikaele%20Kulimoetoke) | [Q20029497](https://www.wikidata.org/wiki/Q20029497) |
| **Vinciane Pirenne-Delforge** | Belgian historian | [Wikipedia](https://fr.wikipedia.org/wiki/Vinciane%20Pirenne-Delforge) | [Q45022692](https://www.wikidata.org/wiki/Q45022692) |
| **Nelly Alba** | Colombian cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Nelly%20Alba) | [Q66715358](https://www.wikidata.org/wiki/Q66715358) |
| **Monica Gschwind** | Swiss politician | [Wikipedia](https://fr.wikipedia.org/wiki/Monica%20Gschwind) | [Q73926943](https://www.wikidata.org/wiki/Q73926943) |

## 1962

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Michael Monroe** | Finnish rock musician | [Wikipedia](https://fr.wikipedia.org/wiki/Michael%20Monroe) | [Q1386535](https://www.wikidata.org/wiki/Q1386535) |
| **Bernard Liautaud** | French entrepreneur | [Wikipedia](https://fr.wikipedia.org/wiki/Bernard%20Liautaud) | [Q2898246](https://www.wikidata.org/wiki/Q2898246) |
| **Lio** | Belgian actress and singer | [Wikipedia](https://fr.wikipedia.org/wiki/Lio) | [Q462403](https://www.wikidata.org/wiki/Q462403) |
| **Martin Hangl** | Swiss alpine skier | [Wikipedia](https://fr.wikipedia.org/wiki/Martin%20Hangl) | [Q547727](https://www.wikidata.org/wiki/Q547727) |
| **Xavier Sala-i-Martin** | Spanish economist | [Wikipedia](https://fr.wikipedia.org/wiki/Xavier%20Sala%20i%20Mart%C3%ADn) | [Q732476](https://www.wikidata.org/wiki/Q732476) |
| **Bruce Robertson** | Canadian rower | [Wikipedia](https://fr.wikipedia.org/wiki/Bruce%20Robertson%20(aviron)) | [Q794682](https://www.wikidata.org/wiki/Q794682) |
| **Tory Burch** | American fashion designer, businesswoman, and philanthropist | [Wikipedia](https://fr.wikipedia.org/wiki/Tory%20Burch) | [Q2945547](https://www.wikidata.org/wiki/Q2945547) |
| **Djamel Amani** | Algerian footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Djamel%20Amani) | [Q3032768](https://www.wikidata.org/wiki/Q3032768) |
| **Philippe Tibeuf** | football player from France | [Wikipedia](https://fr.wikipedia.org/wiki/Philippe%20Tibeuf) | [Q3380785](https://www.wikidata.org/wiki/Q3380785) |
| **Pierre Mikaïloff** | French guitarist | [Wikipedia](https://fr.wikipedia.org/wiki/Pierre%20Mika%C3%AFloff) | [Q3386291](https://www.wikidata.org/wiki/Q3386291) |
| **Gérald Karsenti** | French general director of SAP France | [Wikipedia](https://fr.wikipedia.org/wiki/G%C3%A9rald%20Karsenti) | [Q17315276](https://www.wikidata.org/wiki/Q17315276) |
| **Tetsuya Akikawa** | Japanese singer and owarai tarento | [Wikipedia](https://fr.wikipedia.org/wiki/Durian%20Sukegawa) | [Q24068773](https://www.wikidata.org/wiki/Q24068773) |
| **Ada Ferrer** | American historian and academic | [Wikipedia](https://fr.wikipedia.org/wiki/Ada%20Ferrer) | [Q28457176](https://www.wikidata.org/wiki/Q28457176) |
| **María Isabel García Luis** | Spanish politician | [Wikipedia](https://fr.wikipedia.org/wiki/Mar%C3%ADa%20Isabel%20Garc%C3%ADa%20Luis) | [Q28764929](https://www.wikidata.org/wiki/Q28764929) |
| **Jerry Falwell, Jr.** | American lawyer | [Wikipedia](https://fr.wikipedia.org/wiki/Jerry%20Falwell%20Jr.) | [Q6183563](https://www.wikidata.org/wiki/Q6183563) |

## 1961

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1960

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Adrián Campos** | Spanish racing driver | [Wikipedia](https://fr.wikipedia.org/wiki/Adri%C3%A1n%20Campos) | [Q171456](https://www.wikidata.org/wiki/Q171456) |
| **Thomas Haden Church** | American actor | [Wikipedia](https://fr.wikipedia.org/wiki/Thomas%20Haden%20Church) | [Q311615](https://www.wikidata.org/wiki/Q311615) |
| **Hans van Baalen** | Dutch politician and MEP (1960-2021) | [Wikipedia](https://fr.wikipedia.org/wiki/Hans%20van%20Baalen) | [Q1583347](https://www.wikidata.org/wiki/Q1583347) |
| **Dominique Reynié** | French political scientist | [Wikipedia](https://fr.wikipedia.org/wiki/Dominique%20Reyni%C3%A9) | [Q3035438](https://www.wikidata.org/wiki/Q3035438) |
| **Laurence Abeille** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/Laurence%20Abeille) | [Q3218844](https://www.wikidata.org/wiki/Q3218844) |
| **Yvan Bernier** | Canadian politician | [Wikipedia](https://fr.wikipedia.org/wiki/Yvan%20Bernier) | [Q3573328](https://www.wikidata.org/wiki/Q3573328) |
| **Michelle Scutt** | British athlete | [Wikipedia](https://fr.wikipedia.org/wiki/Michelle%20Probert) | [Q461496](https://www.wikidata.org/wiki/Q461496) |
| **Kim Tae-gyun** | South Korean film director | [Wikipedia](https://fr.wikipedia.org/wiki/Kim%20Tae-gyun) | [Q489095](https://www.wikidata.org/wiki/Q489095) |
| **Douglas Vieira** | Brazilian judoka | [Wikipedia](https://fr.wikipedia.org/wiki/Douglas%20Vieria) | [Q5302061](https://www.wikidata.org/wiki/Q5302061) |
| **Gary Williams** | English footballer/Club Promoter (born 1960) | [Wikipedia](https://fr.wikipedia.org/wiki/Gary%20Williams) | [Q553994](https://www.wikidata.org/wiki/Q553994) |
| **Raanan Rein** | Israeli political writer | [Wikipedia](https://fr.wikipedia.org/wiki/Raanan%20Rein) | [Q12411416](https://www.wikidata.org/wiki/Q12411416) |
| **John Curran** | Irish politician | [Wikipedia](https://fr.wikipedia.org/wiki/John%20Curran%20(homme%20politique)) | [Q6227930](https://www.wikidata.org/wiki/Q6227930) |
| **Tony Willis** | boxer | [Wikipedia](https://fr.wikipedia.org/wiki/Anthony%20Willis) | [Q6243198](https://www.wikidata.org/wiki/Q6243198) |

## 1959

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Colin Fox** | Scottish socialist | [Wikipedia](https://fr.wikipedia.org/wiki/Colin%20Fox) | [Q1108455](https://www.wikidata.org/wiki/Q1108455) |
| **Kazuki Yao** | Japanese voice actor | [Wikipedia](https://fr.wikipedia.org/wiki/Kazuki%20Yao) | [Q166267](https://www.wikidata.org/wiki/Q166267) |
| **Nikos Stavropoulos** | basketball player | [Wikipedia](https://fr.wikipedia.org/wiki/N%C3%ADkos%20Stavr%C3%B3poulos) | [Q1763862](https://www.wikidata.org/wiki/Q1763862) |
| **Francis Ginibre** | French comedian | [Wikipedia](https://fr.wikipedia.org/wiki/Francis%20Ginibre) | [Q3081461](https://www.wikidata.org/wiki/Q3081461) |
| **Thierry Brac de La Perrière** | Bishop of Nevers | [Wikipedia](https://fr.wikipedia.org/wiki/Thierry%20Brac%20de%20La%20Perri%C3%A8re%20(%C3%A9v%C3%AAque)) | [Q328171](https://www.wikidata.org/wiki/Q328171) |
| **Adrie van der Poel** | racing cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Adrie%20van%20der%20Poel) | [Q376580](https://www.wikidata.org/wiki/Q376580) |
| **Ulrike Richter** | East German swimmer | [Wikipedia](https://fr.wikipedia.org/wiki/Ulrike%20Richter) | [Q442443](https://www.wikidata.org/wiki/Q442443) |
| **Kandia Camara** | Ivorian politician | [Wikipedia](https://fr.wikipedia.org/wiki/Kandia%20Camara) | [Q3192595](https://www.wikidata.org/wiki/Q3192595) |
| **Charlie Fancutt** | Australian tennis player | [Wikipedia](https://fr.wikipedia.org/wiki/Charlie%20Fancutt) | [Q5084826](https://www.wikidata.org/wiki/Q5084826) |
| **Eric Michoux** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/%C3%89ric%20Michoux) | [Q65593196](https://www.wikidata.org/wiki/Q65593196) |
| **Boualem Laroum** | Algerian association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Boualem%20Laroum) | [Q117041317](https://www.wikidata.org/wiki/Q117041317) |

## 1958

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Jello Biafra** | American singer and activist (born 1958) | [Wikipedia](https://fr.wikipedia.org/wiki/Jello%20Biafra) | [Q334288](https://www.wikidata.org/wiki/Q334288) |
| **Bobby Farrelly** | American film producer | [Wikipedia](https://fr.wikipedia.org/wiki/Bobby%20Farrelly) | [Q888535](https://www.wikidata.org/wiki/Q888535) |
| **Brad Wenstrup** | American politician in Ohio (born 1958) | [Wikipedia](https://fr.wikipedia.org/wiki/Brad%20Wenstrup) | [Q892413](https://www.wikidata.org/wiki/Q892413) |
| **Sam Hamad** | Canadian politician | [Wikipedia](https://fr.wikipedia.org/wiki/Sam%20Hamad) | [Q921062](https://www.wikidata.org/wiki/Q921062) |
| **Alain Paillou** | French comics artist | [Wikipedia](https://fr.wikipedia.org/wiki/Alain%20Paillou) | [Q2830148](https://www.wikidata.org/wiki/Q2830148) |
| **Derek Lee Ragin** | American counter-tenor | [Wikipedia](https://fr.wikipedia.org/wiki/Derek%20Lee%20Ragin) | [Q3023749](https://www.wikidata.org/wiki/Q3023749) |
| **Lionel Froissart** | French journalist | [Wikipedia](https://fr.wikipedia.org/wiki/Lionel%20Froissart) | [Q3241874](https://www.wikidata.org/wiki/Q3241874) |
| **Pierre Berbizier** | French rugby union footballer and coach | [Wikipedia](https://fr.wikipedia.org/wiki/Pierre%20Berbizier) | [Q3383935](https://www.wikidata.org/wiki/Q3383935) |
| **Scott Peters** | American politician | [Wikipedia](https://fr.wikipedia.org/wiki/Scott%20Peters%20(homme%20politique)) | [Q3791514](https://www.wikidata.org/wiki/Q3791514) |
| **Des Drummond** | Jamaican-British rugby league footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Desmond%20Drummond) | [Q5263450](https://www.wikidata.org/wiki/Q5263450) |
| **Jerry Carl** | American politician (born 1958) | [Wikipedia](https://fr.wikipedia.org/wiki/Jerry%20Carl) | [Q102277702](https://www.wikidata.org/wiki/Q102277702) |
| **Donatella Tesei** | Italian politician | [Wikipedia](https://fr.wikipedia.org/wiki/Donatella%20Tesei) | [Q51027227](https://www.wikidata.org/wiki/Q51027227) |
| **Barbara Creecy** | Member of the National Assembly of South Africa and Minister of Transport | [Wikipedia](https://fr.wikipedia.org/wiki/Barbara%20Creecy) | [Q64711336](https://www.wikidata.org/wiki/Q64711336) |
| **Pampis Kyritsis** | Cypriot politician | [Wikipedia](https://fr.wikipedia.org/wiki/P%C3%A1mbis%20Kyr%C3%ADtsis) | [Q65626251](https://www.wikidata.org/wiki/Q65626251) |

## 1957

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Jon Gries** | American actor, writer, director | [Wikipedia](https://fr.wikipedia.org/wiki/Jon%20Gries) | [Q1319770](https://www.wikidata.org/wiki/Q1319770) |
| **Phyllida Lloyd** | British film and theatre director | [Wikipedia](https://fr.wikipedia.org/wiki/Phyllida%20Lloyd) | [Q237696](https://www.wikidata.org/wiki/Q237696) |
| **Jack Wouterse** | Dutch actor (born 1957) | [Wikipedia](https://fr.wikipedia.org/wiki/Jack%20Wouterse) | [Q327600](https://www.wikidata.org/wiki/Q327600) |
| **Stephen Shellen** | Canadian actor | [Wikipedia](https://fr.wikipedia.org/wiki/Stephen%20Shellen) | [Q328074](https://www.wikidata.org/wiki/Q328074) |
| **Joachim Król** | German actor | [Wikipedia](https://fr.wikipedia.org/wiki/Joachim%20Kr%C3%B3l) | [Q66011](https://www.wikidata.org/wiki/Q66011) |
| **Phil Chevron** | Irish guitarist (1957–2013) | [Wikipedia](https://fr.wikipedia.org/wiki/Phil%20Chevron) | [Q2086113](https://www.wikidata.org/wiki/Q2086113) |
| **Doug Butler** | Canadian ice hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/Doug%20Butler) | [Q3037921](https://www.wikidata.org/wiki/Q3037921) |
| **Grace de Capitani** | Belgian actress | [Wikipedia](https://fr.wikipedia.org/wiki/Grace%20de%20Capitani) | [Q3113027](https://www.wikidata.org/wiki/Q3113027) |
| **Lev Kofman** | Canadian physicist and theoretical physicist (1957-2009) | [Wikipedia](https://fr.wikipedia.org/wiki/Lev%20Kofman) | [Q3237140](https://www.wikidata.org/wiki/Q3237140) |
| **Sam Douglas** | British actor | [Wikipedia](https://fr.wikipedia.org/wiki/Sam%20Douglas) | [Q3470473](https://www.wikidata.org/wiki/Q3470473) |
| **Viliami Tupoulahi Mailefihi Tukuʻaho** | Tongan politician, and rugby union footballer and coach (1957-2014) | [Wikipedia](https://fr.wikipedia.org/wiki/Viliami%20Tupoulahi%20Mailefihi%20Tuku%CA%BBaho) | [Q3558420](https://www.wikidata.org/wiki/Q3558420) |
| **Polycarpe Banlog** | politician in Cameroon | [Wikipedia](https://fr.wikipedia.org/wiki/Polycarpe%20Banlog) | [Q136798865](https://www.wikidata.org/wiki/Q136798865) |
| **Jean-Louis Baugnies** | Belgian bicycle racer | [Wikipedia](https://fr.wikipedia.org/wiki/Jean-Louis%20Baugnies) | [Q19866095](https://www.wikidata.org/wiki/Q19866095) |
| **Marc Nicolas** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Marc%20Nicolas) | [Q28059105](https://www.wikidata.org/wiki/Q28059105) |
| **Daniel Han** | Taiwanese politician | [Wikipedia](https://fr.wikipedia.org/wiki/Han%20Kuo-yu) | [Q8274095](https://www.wikidata.org/wiki/Q8274095) |

## 1956

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Paul Sherwen** | English racing cyclist and journalist (1956–2018) | [Wikipedia](https://fr.wikipedia.org/wiki/Paul%20Sherwen) | [Q2065351](https://www.wikidata.org/wiki/Q2065351) |
| **Edgar Jones** | American basketball player | [Wikipedia](https://fr.wikipedia.org/wiki/Edgar%20Jones) | [Q2343352](https://www.wikidata.org/wiki/Q2343352) |
| **Kelly Curtis** | American actress | [Wikipedia](https://fr.wikipedia.org/wiki/Kelly%20Curtis) | [Q273574](https://www.wikidata.org/wiki/Q273574) |
| **François Gouyette** | French diplomat | [Wikipedia](https://fr.wikipedia.org/wiki/Fran%C3%A7ois%20Gouyette) | [Q3084753](https://www.wikidata.org/wiki/Q3084753) |
| **Iain Milne** | Scotland rugby union footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Iain%20Milne) | [Q3147200](https://www.wikidata.org/wiki/Q3147200) |
| **Lian Ong** | Dutch comics artist | [Wikipedia](https://fr.wikipedia.org/wiki/Lian%20Ong) | [Q3237661](https://www.wikidata.org/wiki/Q3237661) |
| **Lionel Cassan** | television presenter (1956-2002) | [Wikipedia](https://fr.wikipedia.org/wiki/Lionel%20Cassan) | [Q3241832](https://www.wikidata.org/wiki/Q3241832) |
| **Pierre-Édouard Detrez** | French rugby union player | [Wikipedia](https://fr.wikipedia.org/wiki/Pierre-%C3%89douard%20Detrez) | [Q3383592](https://www.wikidata.org/wiki/Q3383592) |
| **Serge Salat** | French architect | [Wikipedia](https://fr.wikipedia.org/wiki/Serge%20Salat) | [Q17353218](https://www.wikidata.org/wiki/Q17353218) |

## 1955

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **David Walsh** | Irish sports journalist | [Wikipedia](https://fr.wikipedia.org/wiki/David%20Walsh%20(journaliste)) | [Q1177071](https://www.wikidata.org/wiki/Q1177071) |
| **Elisabeth Heister-Neumann** | German politician | [Wikipedia](https://fr.wikipedia.org/wiki/Elisabeth%20Heister-Neumann) | [Q1329977](https://www.wikidata.org/wiki/Q1329977) |
| **Santiago Silva Retamales** | Chilean bishop | [Wikipedia](https://fr.wikipedia.org/wiki/Santiago%20Silva%20Retamales) | [Q1768038](https://www.wikidata.org/wiki/Q1768038) |
| **Martti Anhava** | Finnish writer, translator and journalist | [Wikipedia](https://fr.wikipedia.org/wiki/Martti%20Anhava) | [Q2414703](https://www.wikidata.org/wiki/Q2414703) |
| **Marcel Di Domenico** | Luxemburgian footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Marcel%20Di%20Domenico) | [Q2622272](https://www.wikidata.org/wiki/Q2622272) |
| **Arezki Idjerouidene** | French president and chief executive officer (1955-2016) | [Wikipedia](https://fr.wikipedia.org/wiki/Arezki%20Idjerouidene) | [Q2860881](https://www.wikidata.org/wiki/Q2860881) |
| **Joe Charboneau** | American baseball player | [Wikipedia](https://fr.wikipedia.org/wiki/Joe%20Charboneau) | [Q3180016](https://www.wikidata.org/wiki/Q3180016) |
| **Marie Borin** | French writer | [Wikipedia](https://fr.wikipedia.org/wiki/Marie%20Borin) | [Q3292388](https://www.wikidata.org/wiki/Q3292388) |
| **Pierre Merle** | French sociologist | [Wikipedia](https://fr.wikipedia.org/wiki/Pierre%20Merle%20(sociologue)) | [Q3386248](https://www.wikidata.org/wiki/Q3386248) |
| **Jeff Imada** | American stunt performer | [Wikipedia](https://fr.wikipedia.org/wiki/Jeff%20Imada) | [Q6119903](https://www.wikidata.org/wiki/Q6119903) |
| **Bob Sauvé** | Canadian ice hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/Robert%20Sauv%C3%A9) | [Q743647](https://www.wikidata.org/wiki/Q743647) |
| **Alan Taylor** | American historian | [Wikipedia](https://fr.wikipedia.org/wiki/Alan%20Taylor%20(historien)) | [Q15514842](https://www.wikidata.org/wiki/Q15514842) |
| **Patricia Turner** | folklorist and author | [Wikipedia](https://fr.wikipedia.org/wiki/Patricia%20Turner) | [Q17146061](https://www.wikidata.org/wiki/Q17146061) |
| **Hsueh Jui-yuan** | Physician and former Minister of Health and Welfare of Taiwan | [Wikipedia](https://fr.wikipedia.org/wiki/Hsueh%20Jui-yuan) | [Q40272747](https://www.wikidata.org/wiki/Q40272747) |
| **Q136371070** | Togolese jurist | [Wikipedia](https://fr.wikipedia.org/wiki/Koffi%20Ahadzi-Nonou) | [Q136371070](https://www.wikidata.org/wiki/Q136371070) |

## 1954

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Mark Linn-Baker** | American actor | [Wikipedia](https://fr.wikipedia.org/wiki/Mark%20Linn-Baker) | [Q1366440](https://www.wikidata.org/wiki/Q1366440) |
| **Pedro Rodrigues Filho** | Brazilian serial killer (1954–2023) | [Wikipedia](https://fr.wikipedia.org/wiki/Pedro%20Rodrigues%20Filho) | [Q1999429](https://www.wikidata.org/wiki/Q1999429) |
| **Thierry De Cordier** | Belgian visual artist (born 1954) | [Wikipedia](https://fr.wikipedia.org/wiki/Thierry%20De%20Cordier) | [Q2864105](https://www.wikidata.org/wiki/Q2864105) |
| **Cathy Ménard** | French pornographic actress | [Wikipedia](https://fr.wikipedia.org/wiki/Cathy%20M%C3%A9nard) | [Q2942206](https://www.wikidata.org/wiki/Q2942206) |
| **Rena Shereshevskaya** | Russian pianist | [Wikipedia](https://fr.wikipedia.org/wiki/Rena%20Cheretchevska%C3%AFa) | [Q3424703](https://www.wikidata.org/wiki/Q3424703) |
| **Kerry Greenwood** | Australian crime writer | [Wikipedia](https://fr.wikipedia.org/wiki/Kerry%20Greenwood) | [Q5331760](https://www.wikidata.org/wiki/Q5331760) |

## 1953

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Vernon Coaker** | British politician (born 1953) | [Wikipedia](https://fr.wikipedia.org/wiki/Vernon%20Coaker) | [Q285975](https://www.wikidata.org/wiki/Q285975) |
| **Chico Pinheiro** | Brazilian journalist | [Wikipedia](https://fr.wikipedia.org/wiki/Chico%20Pinheiro) | [Q2963401](https://www.wikidata.org/wiki/Q2963401) |
| **Kenny McKinstry** | British rally driver | [Wikipedia](https://fr.wikipedia.org/wiki/Kenny%20McKinstry) | [Q16040681](https://www.wikidata.org/wiki/Q16040681) |
| **Dominique Tedeschi** | French association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Dominique%20Tedeschi) | [Q19502164](https://www.wikidata.org/wiki/Q19502164) |
| **Tshepo Motsepe** | First Lady of South Africa | [Wikipedia](https://fr.wikipedia.org/wiki/Tshepo%20Motsepe) | [Q24234163](https://www.wikidata.org/wiki/Q24234163) |

## 1952

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Sergio Marchionne** | Italian businessman (1952–2018) | [Wikipedia](https://fr.wikipedia.org/wiki/Sergio%20Marchionne) | [Q1229223](https://www.wikidata.org/wiki/Q1229223) |
| **Nikos Salingaros** | Australian academic | [Wikipedia](https://fr.wikipedia.org/wiki/Nikos%20Salingaros) | [Q1400218](https://www.wikidata.org/wiki/Q1400218) |
| **Miguel Ayuso Guixot** | Spanish cardinal, Prefect of the Dicastery for Interreligious Dialogue (1952–2024) | [Wikipedia](https://fr.wikipedia.org/wiki/Miguel%20%C3%81ngel%20Ayuso%20Guixot) | [Q1688598](https://www.wikidata.org/wiki/Q1688598) |
| **Étienne Chatiliez** | French film director | [Wikipedia](https://fr.wikipedia.org/wiki/%C3%89tienne%20Chatiliez) | [Q289512](https://www.wikidata.org/wiki/Q289512) |
| **Estelle Morris, Baroness Morris of Yardley** | British teacher, politician, life peer (born 1952) | [Wikipedia](https://fr.wikipedia.org/wiki/Estelle%20Morris) | [Q333326](https://www.wikidata.org/wiki/Q333326) |
| **Matteo Thun** | Italian architect (born 1952) | [Wikipedia](https://fr.wikipedia.org/wiki/Matteo%20Thun) | [Q874137](https://www.wikidata.org/wiki/Q874137) |
| **Susy De Martini** | Italian politician | [Wikipedia](https://fr.wikipedia.org/wiki/Susy%20De%20Martini) | [Q11714113](https://www.wikidata.org/wiki/Q11714113) |
| **Claire Andrieu** | French historian | [Wikipedia](https://fr.wikipedia.org/wiki/Claire%20Andrieu) | [Q2974999](https://www.wikidata.org/wiki/Q2974999) |
| **Fabienne Thibeault** | Canadian singer-songwriter, naturalized French | [Wikipedia](https://fr.wikipedia.org/wiki/Fabienne%20Thibeault) | [Q3063710](https://www.wikidata.org/wiki/Q3063710) |
| **Marie-Louise Gay** | Canadian illustrator, picture book author and children's writer (born 1952) | [Wikipedia](https://fr.wikipedia.org/wiki/Marie-Louise%20Gay) | [Q3292066](https://www.wikidata.org/wiki/Q3292066) |
| **Mike Milbury** | American ice hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/Michael%20Milbury) | [Q3313457](https://www.wikidata.org/wiki/Q3313457) |
| **Sarbjit Singh Chadha** | Indian singer | [Wikipedia](https://fr.wikipedia.org/wiki/S.S.Chadha) | [Q3459078](https://www.wikidata.org/wiki/Q3459078) |
| **Walter Mantegazza** | Uruguayan footballer (1952-2006) | [Wikipedia](https://fr.wikipedia.org/wiki/Walter%20Mantegazza) | [Q4017958](https://www.wikidata.org/wiki/Q4017958) |
| **Mike Cahill** | American tennis player | [Wikipedia](https://fr.wikipedia.org/wiki/Mike%20Cahill%20(tennis)) | [Q6846222](https://www.wikidata.org/wiki/Q6846222) |

## 1951

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Paul McGuinness** | Irish businessman, music publisher and manager of U2 | [Wikipedia](https://fr.wikipedia.org/wiki/Paul%20McGuinness) | [Q1317221](https://www.wikidata.org/wiki/Q1317221) |
| **Trees Merckx-Van Goey** | Belgian politician and lawyer (born 1951) | [Wikipedia](https://fr.wikipedia.org/wiki/Trees%20Merckx-Van%20Goey) | [Q2071393](https://www.wikidata.org/wiki/Q2071393) |
| **Joe Piscopo** | American actor | [Wikipedia](https://fr.wikipedia.org/wiki/Joe%20Piscopo) | [Q2474995](https://www.wikidata.org/wiki/Q2474995) |
| **Starhawk** | American author, activist and Neopagan | [Wikipedia](https://fr.wikipedia.org/wiki/Starhawk%20(%C3%A9crivaine)) | [Q272205](https://www.wikidata.org/wiki/Q272205) |
| **Dave Fortier** | Canadian ice hockey defenceman | [Wikipedia](https://fr.wikipedia.org/wiki/Dave%20Fortier) | [Q3017161](https://www.wikidata.org/wiki/Q3017161) |
| **Sarclo** | French language Swiss singer | [Wikipedia](https://fr.wikipedia.org/wiki/Sarclo) | [Q3473538](https://www.wikidata.org/wiki/Q3473538) |
| **Václav Junek** | Czech entrepreneur | [Wikipedia](https://fr.wikipedia.org/wiki/V%C3%A1clav%20Junek) | [Q3507640](https://www.wikidata.org/wiki/Q3507640) |
| **Bob Sharpe** | Canadian basketball player | [Wikipedia](https://fr.wikipedia.org/wiki/Bob%20Sharpe) | [Q3641341](https://www.wikidata.org/wiki/Q3641341) |
| **John Garrett** | Canadian ice hockey player | [Wikipedia](https://fr.wikipedia.org/wiki/John%20Garrett) | [Q685506](https://www.wikidata.org/wiki/Q685506) |
| **Luigi Serafini** | Italian basketball player (1951–2020) | [Wikipedia](https://fr.wikipedia.org/wiki/Luigi%20Serafini%20(basket-ball)) | [Q3840154](https://www.wikidata.org/wiki/Q3840154) |
| **John S. Kloppenborg** | Canadian academic | [Wikipedia](https://fr.wikipedia.org/wiki/John%20S.%20Kloppenborg) | [Q4119137](https://www.wikidata.org/wiki/Q4119137) |
| **Emilia Plugaru** | Romanian writer and poet | [Wikipedia](https://fr.wikipedia.org/wiki/Emilia%20Plugaru) | [Q4365856](https://www.wikidata.org/wiki/Q4365856) |
| **Lenny LeBlanc** | American musician | [Wikipedia](https://fr.wikipedia.org/wiki/Lenny%20LeBlanc) | [Q6522968](https://www.wikidata.org/wiki/Q6522968) |

## 1950

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Rudolf Mang** | German weightlifter (1950–2018) | [Wikipedia](https://fr.wikipedia.org/wiki/Rudolf%20Mang) | [Q1651485](https://www.wikidata.org/wiki/Q1651485) |
| **Marie-José Laloy** | Belgian politician | [Wikipedia](https://fr.wikipedia.org/wiki/Marie-Jos%C3%A9%20Laloy) | [Q2749463](https://www.wikidata.org/wiki/Q2749463) |
| **Denis Mathieu** | French association football player (1950-1997) | [Wikipedia](https://fr.wikipedia.org/wiki/Denis%20Mathieu) | [Q3022817](https://www.wikidata.org/wiki/Q3022817) |
| **Marc Jolivet** | French actor, film director and screenwriter | [Wikipedia](https://fr.wikipedia.org/wiki/Marc%20Jolivet) | [Q3288134](https://www.wikidata.org/wiki/Q3288134) |
| **Nicky Marrero** | American percussionist | [Wikipedia](https://fr.wikipedia.org/wiki/Nicky%20Marrero) | [Q3339851](https://www.wikidata.org/wiki/Q3339851) |
| **Han Berger** | Dutch association football player and manager | [Wikipedia](https://fr.wikipedia.org/wiki/Han%20Berger) | [Q440293](https://www.wikidata.org/wiki/Q440293) |
| **Michel Reddé** | French archaeologist, philologist and historian (1950-) | [Wikipedia](https://fr.wikipedia.org/wiki/Michel%20Redd%C3%A9) | [Q16038601](https://www.wikidata.org/wiki/Q16038601) |
| **Susan Damante** | American actress | [Wikipedia](https://fr.wikipedia.org/wiki/Susan%20Damante%20Shaw) | [Q7647731](https://www.wikidata.org/wiki/Q7647731) |

## 1949

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Snakefinger** | English musician, singer and songwriter (1949–1987) | [Wikipedia](https://fr.wikipedia.org/wiki/Snakefinger) | [Q2086125](https://www.wikidata.org/wiki/Q2086125) |
| **Zlatko Mateša** | Prime Minister of Croatia from 1995 to 2000 | [Wikipedia](https://fr.wikipedia.org/wiki/Zlatko%20Mate%C5%A1a) | [Q2625163](https://www.wikidata.org/wiki/Q2625163) |
| **Andrew Weiner** | Canadian writer (1949–2019) | [Wikipedia](https://fr.wikipedia.org/wiki/Andrew%20Weiner) | [Q2846765](https://www.wikidata.org/wiki/Q2846765) |
| **Celia Rees** | English author | [Wikipedia](https://fr.wikipedia.org/wiki/Celia%20Rees) | [Q448421](https://www.wikidata.org/wiki/Q448421) |
| **Serge Vinçon** | French politician (1949-2007) | [Wikipedia](https://fr.wikipedia.org/wiki/Serge%20Vin%C3%A7on) | [Q574408](https://www.wikidata.org/wiki/Q574408) |
| **Tom Corbett** | Governor of Pennsylvania from 2011 to 2015 | [Wikipedia](https://fr.wikipedia.org/wiki/Tom%20Corbett) | [Q881171](https://www.wikidata.org/wiki/Q881171) |
| **Chris Petit** | British writer | [Wikipedia](https://fr.wikipedia.org/wiki/Chris%20Petit) | [Q2964835](https://www.wikidata.org/wiki/Q2964835) |
| **Christian Mouly** | French lawyer and jurist | [Wikipedia](https://fr.wikipedia.org/wiki/Christian%20Mouly) | [Q2965487](https://www.wikidata.org/wiki/Q2965487) |
| **Françoise Dorner** | French actor and writer | [Wikipedia](https://fr.wikipedia.org/wiki/Fran%C3%A7oise%20Dorner) | [Q3086462](https://www.wikidata.org/wiki/Q3086462) |
| **Hugo Philtjens** | Belgian politician | [Wikipedia](https://fr.wikipedia.org/wiki/Hugo%20Philtjens) | [Q3142432](https://www.wikidata.org/wiki/Q3142432) |
| **Lauric Guillaud** | French writer | [Wikipedia](https://fr.wikipedia.org/wiki/Lauric%20Guillaud) | [Q3219636](https://www.wikidata.org/wiki/Q3219636) |
| **Paul Salen** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/Paul%20Salen) | [Q3372149](https://www.wikidata.org/wiki/Q3372149) |
| **Raymond Keruzoré** | French footballer and manager | [Wikipedia](https://fr.wikipedia.org/wiki/Raymond%20Keruzor%C3%A9) | [Q3420959](https://www.wikidata.org/wiki/Q3420959) |
| **Stéphane-Albert Boulais** | Canadian writer | [Wikipedia](https://fr.wikipedia.org/wiki/St%C3%A9phane-Albert%20Boulais) | [Q3501540](https://www.wikidata.org/wiki/Q3501540) |
| **Dean Shek** | Hong Kong actor and producer (1949–2021) | [Wikipedia](https://fr.wikipedia.org/wiki/Dean%20Shek) | [Q5246464](https://www.wikidata.org/wiki/Q5246464) |

## 1948

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1947

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1946

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1945

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1944

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1943

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1942

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1941

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Roger Quemener** | French racewalker (1941–2021) | [Wikipedia](https://fr.wikipedia.org/wiki/Roger%20Quemener) | [Q1860355](https://www.wikidata.org/wiki/Q1860355) |
| **William Lucking** | American actor (1941–2021) | [Wikipedia](https://fr.wikipedia.org/wiki/William%20Lucking) | [Q2324150](https://www.wikidata.org/wiki/Q2324150) |
| **Guy Benoît** | French publisher and poet | [Wikipedia](https://fr.wikipedia.org/wiki/Guy%20Beno%C3%AEt) | [Q3121550](https://www.wikidata.org/wiki/Q3121550) |
| **Dieter Wiedemann** | German cyclist | [Wikipedia](https://fr.wikipedia.org/wiki/Dieter%20Wiedemann) | [Q1223002](https://www.wikidata.org/wiki/Q1223002) |
| **Katherine M. D. Dunbabin** | classical archaeologist | [Wikipedia](https://fr.wikipedia.org/wiki/Katherine%20Dunbabin) | [Q43396302](https://www.wikidata.org/wiki/Q43396302) |
| **Lynn Hershman Leeson** | American artist and filmmaker (born 1941) | [Wikipedia](https://fr.wikipedia.org/wiki/Lynn%20Hershman%20Leeson) | [Q6709060](https://www.wikidata.org/wiki/Q6709060) |

## 1940

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **George Akerlof** | American economist and Koshland Professor of Economics | [Wikipedia](https://fr.wikipedia.org/wiki/George%20Akerlof) | [Q222541](https://www.wikidata.org/wiki/Q222541) |
| **Alton Kelley** | artist (1940–2008) | [Wikipedia](https://fr.wikipedia.org/wiki/Alton%20Kelley) | [Q368015](https://www.wikidata.org/wiki/Q368015) |
| **Marcel Aubour** | French footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Marcel%20Aubour) | [Q386720](https://www.wikidata.org/wiki/Q386720) |
| **Ali Saibou** | President of Niger (1940-2011) | [Wikipedia](https://fr.wikipedia.org/wiki/Ali%20Saibou) | [Q448655](https://www.wikidata.org/wiki/Q448655) |
| **Ernest Sosa** | American philosopher | [Wikipedia](https://fr.wikipedia.org/wiki/Ernest%20Sosa) | [Q1356547](https://www.wikidata.org/wiki/Q1356547) |
| **Annik Beauchamps** | French actress (1940–1995) | [Wikipedia](https://fr.wikipedia.org/wiki/Annik%20Beauchamps) | [Q2851725](https://www.wikidata.org/wiki/Q2851725) |
| **Eugen Cicero** | Romanian-German jazz pianist | [Wikipedia](https://fr.wikipedia.org/wiki/Eugen%20Cicero) | [Q708314](https://www.wikidata.org/wiki/Q708314) |
| **Chuck Rainey** | American bass guitar session musician | [Wikipedia](https://fr.wikipedia.org/wiki/Chuck%20Rainey) | [Q971465](https://www.wikidata.org/wiki/Q971465) |
| **Dan T. Carter** | American historian (born 1940) | [Wikipedia](https://fr.wikipedia.org/wiki/Dan%20T.%20Carter) | [Q5214481](https://www.wikidata.org/wiki/Q5214481) |
| **José Ramón Álvarez Rendueles** | Spanish economist | [Wikipedia](https://fr.wikipedia.org/wiki/Jos%C3%A9%20Ram%C3%B3n%20%C3%81lvarez%20Rendueles) | [Q5945026](https://www.wikidata.org/wiki/Q5945026) |
| **Jerry Adams** | Australian-American molecular biologist | [Wikipedia](https://fr.wikipedia.org/wiki/Jerry%20Adams) | [Q6183179](https://www.wikidata.org/wiki/Q6183179) |

## 1939

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Hanna Johansen** | Swiss writer and translator (1939–2023) | [Wikipedia](https://fr.wikipedia.org/wiki/Hanna%20Johansen) | [Q119768](https://www.wikidata.org/wiki/Q119768) |
| **Carlo Cercignani** | Italian physicist and mathematician (1939–2010) | [Wikipedia](https://fr.wikipedia.org/wiki/Carlo%20Cercignani) | [Q166906](https://www.wikidata.org/wiki/Q166906) |
| **Donald Anderson, Baron Anderson of Swansea** | British politician (born 1939) | [Wikipedia](https://fr.wikipedia.org/wiki/Donald%20Anderson%20(homme%20politique)) | [Q334411](https://www.wikidata.org/wiki/Q334411) |
| **Vittorio Goretti** | Italian amateur astronomer (1939-2016) | [Wikipedia](https://fr.wikipedia.org/wiki/Vittorio%20Goretti) | [Q386980](https://www.wikidata.org/wiki/Q386980) |
| **Krzysztof Zanussi** | Polish producer and film director | [Wikipedia](https://fr.wikipedia.org/wiki/Krzysztof%20Zanussi) | [Q55169](https://www.wikidata.org/wiki/Q55169) |
| **Hidipo Hamutenya** | Namibian politician (1939-2016) | [Wikipedia](https://fr.wikipedia.org/wiki/Hidipo%20Hamutenya) | [Q557014](https://www.wikidata.org/wiki/Q557014) |
| **Angelo Rinaldi** | French writer (1939–2025) | [Wikipedia](https://fr.wikipedia.org/wiki/Angelo%20Rinaldi) | [Q1238522](https://www.wikidata.org/wiki/Q1238522) |
| **Jean-Paul Émin** | French politician (1939–2024) | [Wikipedia](https://fr.wikipedia.org/wiki/Jean-Paul%20%C3%89min) | [Q3168727](https://www.wikidata.org/wiki/Q3168727) |
| **George Lee Butler** | United States general | [Wikipedia](https://fr.wikipedia.org/wiki/George%20Lee%20Butler) | [Q5541630](https://www.wikidata.org/wiki/Q5541630) |
| **Sohen Biln** | Canadian rower (1939–2012) | [Wikipedia](https://fr.wikipedia.org/wiki/Sohen%20Biln) | [Q861113](https://www.wikidata.org/wiki/Q861113) |
| **Frederick Vine** | British geologist (1939–2024) | [Wikipedia](https://fr.wikipedia.org/wiki/Frederick%20Vine) | [Q948019](https://www.wikidata.org/wiki/Q948019) |
| **Peter Sykes** | Australian film director (1939-2006) | [Wikipedia](https://fr.wikipedia.org/wiki/Peter%20Sykes) | [Q964832](https://www.wikidata.org/wiki/Q964832) |
| **James Gadson** | American musician | [Wikipedia](https://fr.wikipedia.org/wiki/James%20Gadson) | [Q15452741](https://www.wikidata.org/wiki/Q15452741) |
| **Barry Howson** | former Canadian basketball player | [Wikipedia](https://fr.wikipedia.org/wiki/Barry%20Howson) | [Q7001495](https://www.wikidata.org/wiki/Q7001495) |
| **Claude Benezra** | French chemist, founder of dermato-chemistry (1939-1992) | [Wikipedia](https://fr.wikipedia.org/wiki/Claude%20Benezra) | [Q59533581](https://www.wikidata.org/wiki/Q59533581) |

## 1938

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Grethe Ingmann** | Danish singer (1938–1990) | [Wikipedia](https://fr.wikipedia.org/wiki/Grethe%20Ingmann) | [Q1546095](https://www.wikidata.org/wiki/Q1546095) |
| **Robin Cocks** | British geologist (1938–2023) | [Wikipedia](https://fr.wikipedia.org/wiki/Robin%20Cocks) | [Q2159740](https://www.wikidata.org/wiki/Q2159740) |
| **Pierre Forgues** | French politician (born 1938) | [Wikipedia](https://fr.wikipedia.org/wiki/Pierre%20Forgues) | [Q3385040](https://www.wikidata.org/wiki/Q3385040) |
| **Satoshi Miyazaki** | Japanese karateka (1938-1993) | [Wikipedia](https://fr.wikipedia.org/wiki/Satoshi%20Miyazaki) | [Q3473980](https://www.wikidata.org/wiki/Q3473980) |
| **Vladimir Karasyov** | Russian chess player (1938-2021) | [Wikipedia](https://fr.wikipedia.org/wiki/Vladimir%20Karassiov) | [Q4214273](https://www.wikidata.org/wiki/Q4214273) |
| **Antje Geerk** | German actress | [Wikipedia](https://fr.wikipedia.org/wiki/Antje%20Geerk) | [Q584689](https://www.wikidata.org/wiki/Q584689) |
| **José Manuel Mourinho Félix** | Portuguese football player/manager (1938-2017) | [Wikipedia](https://fr.wikipedia.org/wiki/F%C3%A9lix%20Mourinho) | [Q639162](https://www.wikidata.org/wiki/Q639162) |
| **Donald Dell** | US tennis player | [Wikipedia](https://fr.wikipedia.org/wiki/Donald%20Dell) | [Q947757](https://www.wikidata.org/wiki/Q947757) |
| **Ian Sloan** | Australian mathematician | [Wikipedia](https://fr.wikipedia.org/wiki/Ian%20Sloan%20(math%C3%A9maticien)) | [Q18373767](https://www.wikidata.org/wiki/Q18373767) |
| **Judy Kimball** | professional golfer | [Wikipedia](https://fr.wikipedia.org/wiki/Judy%20Kimball) | [Q4958804](https://www.wikidata.org/wiki/Q4958804) |
| **Peter Lowe** | British sculptor (1938-) | [Wikipedia](https://fr.wikipedia.org/wiki/Peter%20Lowe) | [Q7175523](https://www.wikidata.org/wiki/Q7175523) |

## 1937

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Clodovil Hernandes** | Brazilian stylist, TV host and politician (1937-2009) | [Wikipedia](https://fr.wikipedia.org/wiki/Clodovil%20Hernandes) | [Q139552](https://www.wikidata.org/wiki/Q139552) |
| **Stella Márquez** | Colombian pageant director and beauty pageant contestant | [Wikipedia](https://fr.wikipedia.org/wiki/Stella%20M%C3%A1rquez) | [Q2493536](https://www.wikidata.org/wiki/Q2493536) |
| **Luis Manuel Rodríguez** | Cuban boxer | [Wikipedia](https://fr.wikipedia.org/wiki/Luis%20Manuel%20Rodr%C3%ADguez) | [Q326667](https://www.wikidata.org/wiki/Q326667) |
| **Ted Nelson** | American information technologist, philosopher, and sociologist | [Wikipedia](https://fr.wikipedia.org/wiki/Ted%20Nelson) | [Q62852](https://www.wikidata.org/wiki/Q62852) |
| **Arthur Schmidt** | American film editor (1937–2023) | [Wikipedia](https://fr.wikipedia.org/wiki/Arthur%20Schmidt) | [Q711370](https://www.wikidata.org/wiki/Q711370) |
| **Jeanne-Marie Ruth-Rolland** | Central African politician | [Wikipedia](https://fr.wikipedia.org/wiki/Jeanne-Marie%20Ruth-Rolland) | [Q15648277](https://www.wikidata.org/wiki/Q15648277) |
| **Axel Bogousslavsky** | French actor | [Wikipedia](https://fr.wikipedia.org/wiki/Axel%20Bogousslavsky) | [Q27962679](https://www.wikidata.org/wiki/Q27962679) |
| **Don Casey** | basketball coach | [Wikipedia](https://fr.wikipedia.org/wiki/Don%20Casey) | [Q3713493](https://www.wikidata.org/wiki/Q3713493) |

## 1936

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Javier Manterola** | Spanish bridge engineer (1936–2024) | [Wikipedia](https://fr.wikipedia.org/wiki/Javier%20Manterola) | [Q118501](https://www.wikidata.org/wiki/Q118501) |
| **Ken Loach** | English film director and screenwriter (born 1936) | [Wikipedia](https://fr.wikipedia.org/wiki/Ken%20Loach) | [Q55238](https://www.wikidata.org/wiki/Q55238) |
| **Gérard Bourgeois** | French composer (1936–2016) | [Wikipedia](https://fr.wikipedia.org/wiki/G%C3%A9rard%20Bourgeois%20(compositeur)) | [Q3123787](https://www.wikidata.org/wiki/Q3123787) |
| **Jean Ibanès** | French politician (1936–1985) | [Wikipedia](https://fr.wikipedia.org/wiki/Jean%20Iban%C3%A8s) | [Q3172689](https://www.wikidata.org/wiki/Q3172689) |
| **Tadanori Yokoo** | Japanese artist and graphic designer (1936-) | [Wikipedia](https://fr.wikipedia.org/wiki/Tadanori%20Yokoo) | [Q3513688](https://www.wikidata.org/wiki/Q3513688) |
| **Lyudmila Verbitskaya** | Russian linguist (1936–2019) | [Wikipedia](https://fr.wikipedia.org/wiki/Lioudmila%20Verbitska%C3%AFa) | [Q4107399](https://www.wikidata.org/wiki/Q4107399) |
| **Nils Wilhjelm** | Danish politician (1936-2018) | [Wikipedia](https://fr.wikipedia.org/wiki/Nils%20Wilhjelm) | [Q4289811](https://www.wikidata.org/wiki/Q4289811) |
| **Barry Howson** | former Canadian basketball player | [Wikipedia](https://fr.wikipedia.org/wiki/Barry%20Howson) | [Q7001495](https://www.wikidata.org/wiki/Q7001495) |

## 1935

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Peggy Seeger** | American folk singer (1935-) | [Wikipedia](https://fr.wikipedia.org/wiki/Peggy%20Seeger) | [Q2067420](https://www.wikidata.org/wiki/Q2067420) |
| **José María Gil-Robles y Gil-Delgado** | Spanish politician (1935–2023) | [Wikipedia](https://fr.wikipedia.org/wiki/Jos%C3%A9%20Mar%C3%ADa%20Gil-Robles%20y%20Gil-Delgado) | [Q682757](https://www.wikidata.org/wiki/Q682757) |

## 1934

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1933

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1932

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1931

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1930

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1929

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Tigran Petrosian** | Soviet Armenian Grandmaster and World Chess Champion | [Wikipedia](https://fr.wikipedia.org/wiki/Tigran%20Petrossian) | [Q180636](https://www.wikidata.org/wiki/Q180636) |
| **Govindasamy Suppiah** | Indian football referee (1929–2012) | [Wikipedia](https://fr.wikipedia.org/wiki/Govindasamy%20Suppiah) | [Q657528](https://www.wikidata.org/wiki/Q657528) |
| **Bud Collins** | US sports journalist and tennis player (1929–2016) | [Wikipedia](https://fr.wikipedia.org/wiki/Bud%20Collins) | [Q1000491](https://www.wikidata.org/wiki/Q1000491) |
| **James Shigeta** | American actor (1929–2014) | [Wikipedia](https://fr.wikipedia.org/wiki/James%20Shigeta) | [Q1400297](https://www.wikidata.org/wiki/Q1400297) |
| **François-Mathurin Gourvès** | French priest (1929-2020) | [Wikipedia](https://fr.wikipedia.org/wiki/Fran%C3%A7ois-Mathurin%20Gourv%C3%A8s) | [Q1450833](https://www.wikidata.org/wiki/Q1450833) |
| **Ward Ruyslinck** | writer (1929–2014) | [Wikipedia](https://fr.wikipedia.org/wiki/Ward%20Ruyslinck) | [Q2246863](https://www.wikidata.org/wiki/Q2246863) |
| **Tomislav Crnković** | Croatian footballer (1929-2009) | [Wikipedia](https://fr.wikipedia.org/wiki/Tomislav%20Crnkovi%C4%87) | [Q764012](https://www.wikidata.org/wiki/Q764012) |
| **Abdallah Al Rassi** | Lebanese politician (1929-1994) | [Wikipedia](https://fr.wikipedia.org/wiki/Abdallah%20Al%20Rassi) | [Q17054393](https://www.wikidata.org/wiki/Q17054393) |
| **Jean Bayle-Lespitau** | French basketball executive (1929–2021) | [Wikipedia](https://fr.wikipedia.org/wiki/Jean%20Bayle-Lespitau) | [Q3170654](https://www.wikidata.org/wiki/Q3170654) |
| **Joe Matthews** | South African politician (1929–2010) | [Wikipedia](https://fr.wikipedia.org/wiki/Joe%20Matthews) | [Q3180124](https://www.wikidata.org/wiki/Q3180124) |
| **Johny Goedert** | Luxembourgish bicycle racer (1929–2013) | [Wikipedia](https://fr.wikipedia.org/wiki/Johny%20Goedert) | [Q3183015](https://www.wikidata.org/wiki/Q3183015) |
| **Maurice Travail** | French actor (1929–1994) | [Wikipedia](https://fr.wikipedia.org/wiki/Maurice%20Travail) | [Q3301466](https://www.wikidata.org/wiki/Q3301466) |
| **Howard Ensign Simmons, Jr.** | American chemist (1929–1997) | [Wikipedia](https://fr.wikipedia.org/wiki/Howard%20Ensign%20Simmons) | [Q5919599](https://www.wikidata.org/wiki/Q5919599) |
| **Luis Calderón** | Peruvian association football player | [Wikipedia](https://fr.wikipedia.org/wiki/Luis%20Calder%C3%B3n) | [Q5982975](https://www.wikidata.org/wiki/Q5982975) |

## 1928

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1927

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1926

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1925

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1924

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1923

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1922

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1921

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1920

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1919

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1918

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1917

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1916

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Kawabata Fumiko** | Japanese singer | [Wikipedia](https://fr.wikipedia.org/wiki/Fumiko%20Kawabata) | [Q11479068](https://www.wikidata.org/wiki/Q11479068) |
| **Steve Raines** | American actor (1916–1996) | [Wikipedia](https://fr.wikipedia.org/wiki/Steve%20Raines) | [Q2347269](https://www.wikidata.org/wiki/Q2347269) |
| **Luigi Scarabello** | Italian footballer and actor (1916-2007) | [Wikipedia](https://fr.wikipedia.org/wiki/Luigi%20Scarabello) | [Q2714577](https://www.wikidata.org/wiki/Q2714577) |
| **Terry Gilkyson** | American musician (1916-1999) | [Wikipedia](https://fr.wikipedia.org/wiki/Terry%20Gilkyson) | [Q359059](https://www.wikidata.org/wiki/Q359059) |
| **Eric F. Goldman** | American historian, Rollins Professor of History at Princeton University, and Presidential advisor (1916-1989) | [Wikipedia](https://fr.wikipedia.org/wiki/Eric%20F.%20Goldman) | [Q5386461](https://www.wikidata.org/wiki/Q5386461) |
| **Einar Englund** | Finnish composer born in Sweden (1916–1999) | [Wikipedia](https://fr.wikipedia.org/wiki/Einar%20Englund) | [Q918402](https://www.wikidata.org/wiki/Q918402) |
| **Ebenezer Ako-Adjei** | Ghanaian politician (1916-2002) | [Wikipedia](https://fr.wikipedia.org/wiki/Ako%20Adjei) | [Q1278627](https://www.wikidata.org/wiki/Q1278627) |
| **Sarah Carneson** | South African labour organizer and anti-apartheid activist (1916-2015) | [Wikipedia](https://fr.wikipedia.org/wiki/Sarah%20Carneson) | [Q27777791](https://www.wikidata.org/wiki/Q27777791) |

## 1915

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Aïssat Idir** | Algerian trade unionist | [Wikipedia](https://fr.wikipedia.org/wiki/A%C3%AFssat%20Idir) | [Q2876427](https://www.wikidata.org/wiki/Q2876427) |
| **Marcel Cadieux** | Canadian diplomat (1915-1981) | [Wikipedia](https://fr.wikipedia.org/wiki/Marcel%20Cadieux) | [Q3288761](https://www.wikidata.org/wiki/Q3288761) |
| **Gunther Gerzs** | Hungarian-Mexican painter, designer and director and screenwriter for film and theatre (1915-2000) | [Wikipedia](https://fr.wikipedia.org/wiki/Gunther%20Gerzso) | [Q352356](https://www.wikidata.org/wiki/Q352356) |
| **Mario Echandi Jiménez** | President of Costa Rica (1915-2011) | [Wikipedia](https://fr.wikipedia.org/wiki/Mario%20Echandi%20Jim%C3%A9nez) | [Q365359](https://www.wikidata.org/wiki/Q365359) |
| **Elena Fabrizi** | Italian actress (1915–1993) | [Wikipedia](https://fr.wikipedia.org/wiki/Elena%20Fabrizi) | [Q3721419](https://www.wikidata.org/wiki/Q3721419) |
| **Mirosław Ferić** | Polish flying ace | [Wikipedia](https://fr.wikipedia.org/wiki/Miros%C5%82aw%20Feri%C4%87) | [Q3817059](https://www.wikidata.org/wiki/Q3817059) |
| **Paul Postaire** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Paul%20Postaire) | [Q108934384](https://www.wikidata.org/wiki/Q108934384) |
| **Hellmuth Marx** | Austrian sculptor | [Wikipedia](https://fr.wikipedia.org/wiki/Hellmuth%20Marx) | [Q18020832](https://www.wikidata.org/wiki/Q18020832) |

## 1914

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Gertrud Heinzelmann** | Swiss suffragist (1914-1999) | [Wikipedia](https://fr.wikipedia.org/wiki/Gertrud%20Heinzelmann) | [Q1515573](https://www.wikidata.org/wiki/Q1515573) |
| **John Van Alphen** | Belgian association football player (1914-1961) | [Wikipedia](https://fr.wikipedia.org/wiki/John%20Van%20Alphen) | [Q2069087](https://www.wikidata.org/wiki/Q2069087) |
| **Georges Cheylan** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Georges%20Cheylan) | [Q3102474](https://www.wikidata.org/wiki/Q3102474) |
| **Julián Marías** | Spanish philosopher (1914-2005) | [Wikipedia](https://fr.wikipedia.org/wiki/Juli%C3%A1n%20Mar%C3%ADas) | [Q520726](https://www.wikidata.org/wiki/Q520726) |
| **John Hersey** | American journalist, novelist, professor (1914-1993) | [Wikipedia](https://fr.wikipedia.org/wiki/John%20Hersey) | [Q535812](https://www.wikidata.org/wiki/Q535812) |
| **Salvador Molina** | Spanish bicycle racer (1914-1982) | [Wikipedia](https://fr.wikipedia.org/wiki/Salvador%20Molina) | [Q611105](https://www.wikidata.org/wiki/Q611105) |
| **Manuel Perez** | Mexican American animator and animation director | [Wikipedia](https://fr.wikipedia.org/wiki/Manuel%20Perez%20(animateur)) | [Q14914635](https://www.wikidata.org/wiki/Q14914635) |
| **Nathan Hosanski** | French rabbi | [Wikipedia](https://fr.wikipedia.org/wiki/Nathan%20Hosanski) | [Q3336734](https://www.wikidata.org/wiki/Q3336734) |
| **Marixa** | Spanish painter (1914-1995) | [Wikipedia](https://fr.wikipedia.org/wiki/Marixa) | [Q42887322](https://www.wikidata.org/wiki/Q42887322) |
| **Kenneth Setton** | American medieval historian (1914-1995) | [Wikipedia](https://fr.wikipedia.org/wiki/Kenneth%20Setton) | [Q6390682](https://www.wikidata.org/wiki/Q6390682) |

## 1913

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1912

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1911

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1910

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1909

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1908

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1907

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1906

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1905

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1904

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1903

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1902

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **F. F. E. Yeo-Thomas** | Special operations executive personnel (1902–1964) | [Wikipedia](https://fr.wikipedia.org/wiki/Forest%20Yeo-Thomas) | [Q1294168](https://www.wikidata.org/wiki/Q1294168) |
| **Auguste Gouirand** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Auguste%20Gouirand) | [Q2871208](https://www.wikidata.org/wiki/Q2871208) |
| **Philip J. Nel** | South African rugby union footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Flip%20Nel) | [Q3073758](https://www.wikidata.org/wiki/Q3073758) |
| **Chae Man-shik** | South Korean writer (1902-1950) | [Wikipedia](https://fr.wikipedia.org/wiki/Chae%20Man-sik) | [Q623552](https://www.wikidata.org/wiki/Q623552) |
| **Sammy Fain** | American composer (1902-1989) | [Wikipedia](https://fr.wikipedia.org/wiki/Sammy%20Fain) | [Q742896](https://www.wikidata.org/wiki/Q742896) |
| **Hubert Schardin** | German photographer and cinematographer (1902–1965) | [Wikipedia](https://fr.wikipedia.org/wiki/Hubert%20Schardin) | [Q88468](https://www.wikidata.org/wiki/Q88468) |

## 1901

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Nadia Russo** | Romanian aviator (1901–1988) | [Wikipedia](https://fr.wikipedia.org/wiki/Nadia%20Russo) | [Q4401077](https://www.wikidata.org/wiki/Q4401077) |
| **Miklós Nyiszli** | Jewish prisoner at the Auschwitz concentration camp (1901–1956) | [Wikipedia](https://fr.wikipedia.org/wiki/Mikl%C3%B3s%20Nyiszli) | [Q550391](https://www.wikidata.org/wiki/Q550391) |

## 1900

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Hubert Jedin** | German theologian and historian (1900-1980) | [Wikipedia](https://fr.wikipedia.org/wiki/Hubert%20Jedin) | [Q67941](https://www.wikidata.org/wiki/Q67941) |
| **Martin Bormann** | German Nazi Party official and head of the Nazi Party Chancellery (1900–1945) | [Wikipedia](https://fr.wikipedia.org/wiki/Martin%20Bormann) | [Q76367](https://www.wikidata.org/wiki/Q76367) |
| **Johannes Maas** | Dutch racing cyclist (1900-1977) | [Wikipedia](https://fr.wikipedia.org/wiki/Johannes%20Maas) | [Q127594](https://www.wikidata.org/wiki/Q127594) |
| **Renata Viganò** | Italian writer (1900–1976) | [Wikipedia](https://fr.wikipedia.org/wiki/Renata%20Vigan%C3%B2) | [Q2263028](https://www.wikidata.org/wiki/Q2263028) |
| **Giulio Cesare Silvagni** | French actor and writer (1900-1984) | [Wikipedia](https://fr.wikipedia.org/wiki/Giulio%20Cesare%20Silvagni) | [Q3107932](https://www.wikidata.org/wiki/Q3107932) |
| **Hermann Reutter** | German musician | [Wikipedia](https://fr.wikipedia.org/wiki/Hermann%20Reutter) | [Q314867](https://www.wikidata.org/wiki/Q314867) |
| **Juliette Milette** | Canadian organist and writer (1900-1992) | [Wikipedia](https://fr.wikipedia.org/wiki/Juliette%20Milette) | [Q3189770](https://www.wikidata.org/wiki/Q3189770) |
| **Marcel Stürmel** | Alsatian politician (1900–1972) | [Wikipedia](https://fr.wikipedia.org/wiki/Marcel%20St%C3%BCrmel) | [Q3289422](https://www.wikidata.org/wiki/Q3289422) |
| **Paul Dupré-Lafon** | French architect (1900–1971) | [Wikipedia](https://fr.wikipedia.org/wiki/Paul%20Dupr%C3%A9-Lafon) | [Q3371135](https://www.wikidata.org/wiki/Q3371135) |
| **Hugo Pesce** | Peruvian physician (1900–1969) | [Wikipedia](https://fr.wikipedia.org/wiki/Hugo%20Pesce) | [Q4360127](https://www.wikidata.org/wiki/Q4360127) |
| **James Cooper** | Canadian politician | [Wikipedia](https://fr.wikipedia.org/wiki/James%20Cooper%20(homme%20politique%20ontarien)) | [Q6131709](https://www.wikidata.org/wiki/Q6131709) |
| **Evelyn Irons** | Scottish journalist | [Wikipedia](https://fr.wikipedia.org/wiki/Evelyn%20Irons) | [Q737545](https://www.wikidata.org/wiki/Q737545) |
| **Maury Thibaut de Maisières** | Belgian historian | [Wikipedia](https://fr.wikipedia.org/wiki/Maurice%20Thibaut%20de%20Maisi%C3%A8res) | [Q18414768](https://www.wikidata.org/wiki/Q18414768) |
| **Alfred Jaunin** | Swiss politician (1900-1986) | [Wikipedia](https://fr.wikipedia.org/wiki/Alfred%20Jaunin) | [Q78076711](https://www.wikidata.org/wiki/Q78076711) |

## 1899

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1898

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **M. C. Escher** | Dutch graphic artist (1898–1972) | [Wikipedia](https://fr.wikipedia.org/wiki/Maurits%20Cornelis%20Escher) | [Q1470](https://www.wikidata.org/wiki/Q1470) |
| **Gerhard Wilck** | German commander of Aachen (1898-1985) | [Wikipedia](https://fr.wikipedia.org/wiki/Gerhard%20Wilck) | [Q70340](https://www.wikidata.org/wiki/Q70340) |
| **Marcel Abraham** | French poet (1898-1955) | [Wikipedia](https://fr.wikipedia.org/wiki/Marcel%20Abraham) | [Q3288603](https://www.wikidata.org/wiki/Q3288603) |
| **Rolando patch** | British soldier, last soldier to serve in the trenches of World War I | [Wikipedia](https://fr.wikipedia.org/wiki/Harry%20Patch) | [Q363644](https://www.wikidata.org/wiki/Q363644) |
| **Latife Uşşakî** | Wife of Mustafa Kemal Atatürk and First Lady of Turkey (1898-1975) | [Wikipedia](https://fr.wikipedia.org/wiki/Latife%20U%C5%9F%C5%9Faki) | [Q464994](https://www.wikidata.org/wiki/Q464994) |
| **Carl Hermann** | German physicist (1898-1961) | [Wikipedia](https://fr.wikipedia.org/wiki/Carl%20Hermann) | [Q77282](https://www.wikidata.org/wiki/Q77282) |
| **Friedrich Skade** | German painter (1898-1971) | [Wikipedia](https://fr.wikipedia.org/wiki/Fritz%20Skade) | [Q11970236](https://www.wikidata.org/wiki/Q11970236) |

## 1897

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **E. L. M. Burns** | Canadian general (1897–1985) | [Wikipedia](https://fr.wikipedia.org/wiki/Eedson%20Louis%20Millard%20Burns) | [Q3048852](https://www.wikidata.org/wiki/Q3048852) |
| **Umberto Melnati** | Italian actor (1897-1979) | [Wikipedia](https://fr.wikipedia.org/wiki/Umberto%20Melnati) | [Q4003436](https://www.wikidata.org/wiki/Q4003436) |
| **Traycho Kostov** | Bulgarian politician (1897-1949) | [Wikipedia](https://fr.wikipedia.org/wiki/Tra%C3%AFcho%20Kostov) | [Q956654](https://www.wikidata.org/wiki/Q956654) |
| **Menina Izildinha** | Portuguese child folk saint | [Wikipedia](https://fr.wikipedia.org/wiki/Menina%20Izildinha) | [Q10328665](https://www.wikidata.org/wiki/Q10328665) |

## 1896

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Rudolf Petersson** | Swedish comic creator (1896–1970) | [Wikipedia](https://fr.wikipedia.org/wiki/Rudolf%20Petersson) | [Q1784957](https://www.wikidata.org/wiki/Q1784957) |
| **Rudolph Scholz** | American rugby union player (1896-1981) | [Wikipedia](https://fr.wikipedia.org/wiki/Rudy%20Scholz) | [Q1805101](https://www.wikidata.org/wiki/Q1805101) |
| **Alain Le Marc'hadour** | French politician and physician | [Wikipedia](https://fr.wikipedia.org/wiki/Alain%20Le%20Marc'hadour) | [Q19360987](https://www.wikidata.org/wiki/Q19360987) |
| **Louise Fazenda** | American actress (1895-1962) | [Wikipedia](https://fr.wikipedia.org/wiki/Louise%20Fazenda) | [Q450986](https://www.wikidata.org/wiki/Q450986) |
| **Cedric Howell** | Australian flying ace of the First World War | [Wikipedia](https://fr.wikipedia.org/wiki/Cedric%20Howell) | [Q5057114](https://www.wikidata.org/wiki/Q5057114) |

## 1895

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Ruben Rausing** | Swedish businessman (1895–1983) | [Wikipedia](https://fr.wikipedia.org/wiki/Ruben%20Rausing) | [Q1937358](https://www.wikidata.org/wiki/Q1937358) |
| **Felix Adler** | American clown | [Wikipedia](https://fr.wikipedia.org/wiki/Felix%20Adler%20(clown)) | [Q3068147](https://www.wikidata.org/wiki/Q3068147) |
| **Liguori Lacombe** | Canadian politician (1895–1957) | [Wikipedia](https://fr.wikipedia.org/wiki/Liguori%20Lacombe) | [Q3240688](https://www.wikidata.org/wiki/Q3240688) |
| **Louise Fazenda** | American actress (1895-1962) | [Wikipedia](https://fr.wikipedia.org/wiki/Louise%20Fazenda) | [Q450986](https://www.wikidata.org/wiki/Q450986) |
| **Sam Wooding** | American jazz pianist (1895–1985) | [Wikipedia](https://fr.wikipedia.org/wiki/Sam%20Wooding) | [Q487124](https://www.wikidata.org/wiki/Q487124) |
| **Slavko Osterc** | Slovenian composer (1895-1941) | [Wikipedia](https://fr.wikipedia.org/wiki/Slavko%20Osterc) | [Q714370](https://www.wikidata.org/wiki/Q714370) |
| **Roger Matéo** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Roger%20Mat%C3%A9o) | [Q135217018](https://www.wikidata.org/wiki/Q135217018) |

## 1894

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1893

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1892

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1891

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1890

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1889

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1888

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1887

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1886

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1885

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1884

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1883

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1882

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1881

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1880

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Carl Van Vechten** | American writer and photographer (1880–1964) | [Wikipedia](https://fr.wikipedia.org/wiki/Carl%20Van%20Vechten) | [Q312851](https://www.wikidata.org/wiki/Q312851) |
| **André Derain** | French painter and engraver (1880–1954) | [Wikipedia](https://fr.wikipedia.org/wiki/Andr%C3%A9%20Derain) | [Q156272](https://www.wikidata.org/wiki/Q156272) |
| **Russell Simpson** | American actor (1880–1959) | [Wikipedia](https://fr.wikipedia.org/wiki/Russell%20Simpson) | [Q1196052](https://www.wikidata.org/wiki/Q1196052) |
| **Henri de La Porte** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/Henri%20de%20La%20Porte) | [Q16025896](https://www.wikidata.org/wiki/Q16025896) |
| **Paul Haviland** | French-American photographer and writer (1880-1950) | [Wikipedia](https://fr.wikipedia.org/wiki/Paul%20Haviland) | [Q2580510](https://www.wikidata.org/wiki/Q2580510) |
| **Manuel Corona** | Cuban musician | [Wikipedia](https://fr.wikipedia.org/wiki/Manuel%20Corona) | [Q3286792](https://www.wikidata.org/wiki/Q3286792) |
| **René Béhaine** | French writer (1880–1966) | [Wikipedia](https://fr.wikipedia.org/wiki/Ren%C3%A9%20B%C3%A9haine) | [Q3425944](https://www.wikidata.org/wiki/Q3425944) |
| **Gaspar Lefebvre** | French monk (1880-1966) | [Wikipedia](https://fr.wikipedia.org/wiki/Gaspar%20Lefebvre) | [Q771131](https://www.wikidata.org/wiki/Q771131) |
| **Louis Foisil** | French poet (1880-1943) | [Wikipedia](https://fr.wikipedia.org/wiki/Louis%20Foisil) | [Q78627810](https://www.wikidata.org/wiki/Q78627810) |
| **Maurice Troillet** | Swiss politician (1880-1961) | [Wikipedia](https://fr.wikipedia.org/wiki/Maurice%20Troillet) | [Q94816415](https://www.wikidata.org/wiki/Q94816415) |

## 1879

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Louis Grogna** | cyclist (1879-1940) | [Wikipedia](https://fr.wikipedia.org/wiki/Louis%20Grogna) | [Q1871701](https://www.wikidata.org/wiki/Q1871701) |
| **Aino Alli** | Finnish artist | [Wikipedia](https://fr.wikipedia.org/wiki/Aino%20Alli) | [Q23040396](https://www.wikidata.org/wiki/Q23040396) |
| **Alfred Smyth** | Samoan politician | [Wikipedia](https://fr.wikipedia.org/wiki/Alfred%20Smyth) | [Q61455139](https://www.wikidata.org/wiki/Q61455139) |
| **Alwin Neuß** | German actor (1879-1935) | [Wikipedia](https://fr.wikipedia.org/wiki/Alwin%20Neu%C3%9F) | [Q99891](https://www.wikidata.org/wiki/Q99891) |

## 1878

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Agustín Edwards** | Chilean entrepreneur, politician and diplomat (1878-1941) | [Wikipedia](https://fr.wikipedia.org/wiki/Agustin%20Edwards) | [Q11952](https://www.wikidata.org/wiki/Q11952) |
| **Guillaume-Ernest Pellus** | French stained-glass artist | [Wikipedia](https://fr.wikipedia.org/wiki/Guillaume-Ernest%20Pellus) | [Q16640483](https://www.wikidata.org/wiki/Q16640483) |
| **Bazar Baradiyn** | Russian writer (1878-1937) | [Wikipedia](https://fr.wikipedia.org/wiki/Bazar%20Baradi%C3%AFne) | [Q4077632](https://www.wikidata.org/wiki/Q4077632) |
| **Sigrid Sundgren-Schnéevoigt** | Finnish pianist | [Wikipedia](https://fr.wikipedia.org/wiki/Sigrid%20Sundgren-Schn%C3%A9evoigt) | [Q4977474](https://www.wikidata.org/wiki/Q4977474) |
| **Victor Cadet** | French swimmer (1878–1911) | [Wikipedia](https://fr.wikipedia.org/wiki/Victor%20Cadet) | [Q759718](https://www.wikidata.org/wiki/Q759718) |

## 1877

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Henri Baulig** | French geographer (1877–1962) | [Wikipedia](https://fr.wikipedia.org/wiki/Henri%20Baulig) | [Q3130639](https://www.wikidata.org/wiki/Q3130639) |
| **William Fazan** | British film actor | [Wikipedia](https://fr.wikipedia.org/wiki/William%20Fazan) | [Q44181253](https://www.wikidata.org/wiki/Q44181253) |
| **Georges Joseph Demotte** | international art dealer (1877-1923) | [Wikipedia](https://fr.wikipedia.org/wiki/Georges%20Demotte) | [Q5541172](https://www.wikidata.org/wiki/Q5541172) |

## 1876

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Émile Torcheboeuf** | French long jumper (1876–1950) | [Wikipedia](https://fr.wikipedia.org/wiki/%C3%89mile%20Torcheb%C5%93uf) | [Q129035](https://www.wikidata.org/wiki/Q129035) |
| **Thomas Crerar** | Western Canadian politician (1876-1975) | [Wikipedia](https://fr.wikipedia.org/wiki/Thomas%20Alexander%20Crerar) | [Q1368799](https://www.wikidata.org/wiki/Q1368799) |
| **William Carr** | American rower (1876-1942) | [Wikipedia](https://fr.wikipedia.org/wiki/William%20Carr%20(aviron)) | [Q1813622](https://www.wikidata.org/wiki/Q1813622) |
| **Pierre Paul Girieud** | French painter (1876-1948) | [Wikipedia](https://fr.wikipedia.org/wiki/Pierre%20Girieud) | [Q2093494](https://www.wikidata.org/wiki/Q2093494) |
| **Charles Genty** | French painter (1876-1956) | [Wikipedia](https://fr.wikipedia.org/wiki/Charles%20Genty) | [Q2959188](https://www.wikidata.org/wiki/Q2959188) |

## 1875

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Charles Moravia** | Haitian poet, dramatist, teacher, and diplomat (1875-1938) | [Wikipedia](https://fr.wikipedia.org/wiki/Charles%20Moravia) | [Q2959853](https://www.wikidata.org/wiki/Q2959853) |
| **Henri Hertz** | French journalist (1875–1966) | [Wikipedia](https://fr.wikipedia.org/wiki/Henri%20Hertz) | [Q3131267](https://www.wikidata.org/wiki/Q3131267) |
| **Edith How-Martyn** | British suffragette (1875-1954) | [Wikipedia](https://fr.wikipedia.org/wiki/Edith%20How-Martyn) | [Q5338572](https://www.wikidata.org/wiki/Q5338572) |
| **John Lawrence Stansell** | Canadian politician | [Wikipedia](https://fr.wikipedia.org/wiki/John%20Lawrence%20Stansell) | [Q6244206](https://www.wikidata.org/wiki/Q6244206) |

## 1874

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Harold Kitson** | South African tennis player (1874-1951) | [Wikipedia](https://fr.wikipedia.org/wiki/Harold%20Kitson) | [Q1034091](https://www.wikidata.org/wiki/Q1034091) |
| **Rufino Blanco Fombona** | Venezuelan writer (1874-1944) | [Wikipedia](https://fr.wikipedia.org/wiki/Rufino%20Blanco%20Fombona) | [Q3082880](https://www.wikidata.org/wiki/Q3082880) |
| **Grant Mitchell** | American actor (1874-1957) | [Wikipedia](https://fr.wikipedia.org/wiki/Grant%20Mitchell) | [Q3115403](https://www.wikidata.org/wiki/Q3115403) |

## 1873

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Clara Ward, Princesse de Caraman-Chimay** | American performer and Belgian princess (1873–1916) | [Wikipedia](https://fr.wikipedia.org/wiki/Clara%20Ward) | [Q1095268](https://www.wikidata.org/wiki/Q1095268) |
| **Edwards Davis** | American actor, playwright, and pastor (1873-1936) | [Wikipedia](https://fr.wikipedia.org/wiki/Edwards%20Davis) | [Q21664342](https://www.wikidata.org/wiki/Q21664342) |
| **Eduardo Chicharro y Agüera** | Spanish painter (1873-1949) | [Wikipedia](https://fr.wikipedia.org/wiki/Eduardo%20Chicharro%20y%20Ag%C3%BCera) | [Q3815373](https://www.wikidata.org/wiki/Q3815373) |

## 1872

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Jean Sendrail** | French veterinarian and surgeon | [Wikipedia](https://fr.wikipedia.org/wiki/Jean%20Sendrail) | [Q16027735](https://www.wikidata.org/wiki/Q16027735) |
| **Georges Krier** | French composer | [Wikipedia](https://fr.wikipedia.org/wiki/Georges%20Krier) | [Q3102979](https://www.wikidata.org/wiki/Q3102979) |
| **Ulrich Hübner** | German artist (1872-1932) | [Wikipedia](https://fr.wikipedia.org/wiki/Ulrich%20H%C3%BCbner) | [Q877843](https://www.wikidata.org/wiki/Q877843) |
| **Bonaventura Cerretti** | Italian Catholic priest and professor (1872–1933) | [Wikipedia](https://fr.wikipedia.org/wiki/Bonaventura%20Cerretti) | [Q892126](https://www.wikidata.org/wiki/Q892126) |

## 1871

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Georges de Burlet** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Georges%20de%20Burlet) | [Q133538819](https://www.wikidata.org/wiki/Q133538819) |
| **Lyonel Feininger** | German-American painter (1871–1956) | [Wikipedia](https://fr.wikipedia.org/wiki/Lyonel%20Feininger) | [Q158255](https://www.wikidata.org/wiki/Q158255) |
| **James Weldon Johnson** | American writer and activist (1871–1938) | [Wikipedia](https://fr.wikipedia.org/wiki/James%20Weldon%20Johnson) | [Q478450](https://www.wikidata.org/wiki/Q478450) |

## 1870

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Georges Delcoigne** | Belgian architect (1870–1916) | [Wikipedia](https://fr.wikipedia.org/wiki/Georges%20Delcoigne) | [Q2192967](https://www.wikidata.org/wiki/Q2192967) |
| **Robert Picard** | Belgian painter (1870-1941) | [Wikipedia](https://fr.wikipedia.org/wiki/Robert%20Picard%20(peintre)) | [Q3436074](https://www.wikidata.org/wiki/Q3436074) |
| **Bernardino Nogara** | Italian financial advisor (1870–1958) | [Wikipedia](https://fr.wikipedia.org/wiki/Bernardino%20Nogara) | [Q3638724](https://www.wikidata.org/wiki/Q3638724) |

## 1869

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Fabian Ware** | British Army general (1869–1949) | [Wikipedia](https://fr.wikipedia.org/wiki/Fabian%20Ware) | [Q1390334](https://www.wikidata.org/wiki/Q1390334) |
| **Mikhail Sablin** | Admiral of the Imperial Russian Navy (1869-1920) | [Wikipedia](https://fr.wikipedia.org/wiki/Mikha%C3%AFl%20Sabline) | [Q2079463](https://www.wikidata.org/wiki/Q2079463) |
| **André Lefèvre** | French politician (1869-1929) | [Wikipedia](https://fr.wikipedia.org/wiki/Andr%C3%A9%20Lef%C3%A8vre) | [Q768982](https://www.wikidata.org/wiki/Q768982) |
| **Prince Aloys of Liechtenstein** | (1869-1955) Prince of Liechtenstein | [Wikipedia](https://fr.wikipedia.org/wiki/Alo%C3%AFs%20de%20Liechtenstein%20(1869-1955)) | [Q78567](https://www.wikidata.org/wiki/Q78567) |

## 1868

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Augustin Chaboseau** | French journalist, historian, and occultist (1868-1946) | [Wikipedia](https://fr.wikipedia.org/wiki/Augustin%20Chaboseau) | [Q2667301](https://www.wikidata.org/wiki/Q2667301) |
| **Kazi Dawa Samdup** | Indian translator (1868–1922) | [Wikipedia](https://fr.wikipedia.org/wiki/Lama%20Kazi%20Dawa%20Samdup) | [Q3216562](https://www.wikidata.org/wiki/Q3216562) |

## 1867

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Flora Finch** | British-born film actress (1867-1940) | [Wikipedia](https://fr.wikipedia.org/wiki/Flora%20Finch) | [Q2070099](https://www.wikidata.org/wiki/Q2070099) |
| **Jean Bousquet** | French unionist (1867-1925) | [Wikipedia](https://fr.wikipedia.org/wiki/Jean%20Bousquet%20(syndicaliste)) | [Q25395975](https://www.wikidata.org/wiki/Q25395975) |
| **John Robert Gregg** | Irish inventor and writer (1867-1948) | [Wikipedia](https://fr.wikipedia.org/wiki/John%20Robert%20Gregg) | [Q254305](https://www.wikidata.org/wiki/Q254305) |
| **Henry Lawson** | Australian writer and poet (1867–1922) | [Wikipedia](https://fr.wikipedia.org/wiki/Henry%20Lawson) | [Q453577](https://www.wikidata.org/wiki/Q453577) |
| **Heinrich Bischoff** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Heinrich%20Bischoff) | [Q67596338](https://www.wikidata.org/wiki/Q67596338) |

## 1866

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Nicolas Daneau** | Belgian composer | [Wikipedia](https://fr.wikipedia.org/wiki/Nicolas%20Daneau) | [Q29020989](https://www.wikidata.org/wiki/Q29020989) |
| **Pierre Marc Antoine Dufaux** | enamel painter and curator (1866-1936) | [Wikipedia](https://fr.wikipedia.org/wiki/Pierre%20Marc%20Antoine%20Dufaux) | [Q29913484](https://www.wikidata.org/wiki/Q29913484) |
| **Otto Haberer** | Swiss painter (1866-1941) | [Wikipedia](https://fr.wikipedia.org/wiki/Otto%20Haberer) | [Q3357808](https://www.wikidata.org/wiki/Q3357808) |
| **Reginald Barlow** | actor (1866-1943) | [Wikipedia](https://fr.wikipedia.org/wiki/Reginald%20Barlow) | [Q3423495](https://www.wikidata.org/wiki/Q3423495) |

## 1865

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Charles Boutet** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/Charles%20Boutet) | [Q15971895](https://www.wikidata.org/wiki/Q15971895) |
| **Susan La Flesche Picotte** | Omaha Native American, physician, and reformer (1865-1915) | [Wikipedia](https://fr.wikipedia.org/wiki/Susan%20La%20Flesche%20Picotte) | [Q2009201](https://www.wikidata.org/wiki/Q2009201) |

## 1864

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Isidore Philbois** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/Isidore%20Philbois) | [Q16026337](https://www.wikidata.org/wiki/Q16026337) |
| **Harriet Ford** | American actress and playwright | [Wikipedia](https://fr.wikipedia.org/wiki/Harriet%20Ford) | [Q43021640](https://www.wikidata.org/wiki/Q43021640) |
| **Aleksey Shakhmatov** | Russian philologist (1864–1920) | [Wikipedia](https://fr.wikipedia.org/wiki/Alexe%C3%AF%20Chakhmatov) | [Q729707](https://www.wikidata.org/wiki/Q729707) |

## 1863

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1862

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1861

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1860

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1859

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1858

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1857

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1856

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1855

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1854

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1853

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1852

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1851

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1850

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1849

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1848

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1847

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1846

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1845

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Robert Dohme** | German librarian and art historian (1845–1893) | [Wikipedia](https://fr.wikipedia.org/wiki/Robert%20Dohme) | [Q103590](https://www.wikidata.org/wiki/Q103590) |
| **Marguerite Pinès de Merbitz** | French painter (1845–1931) | [Wikipedia](https://fr.wikipedia.org/wiki/Marguerite%20Pin%C3%A8s%20de%20Merbitz) | [Q111371639](https://www.wikidata.org/wiki/Q111371639) |
| **Joseph-Samuel Farinet** | Swiss personality of Italian origin, known for money counterfeiting | [Wikipedia](https://fr.wikipedia.org/wiki/Joseph-Samuel%20Farinet) | [Q124856](https://www.wikidata.org/wiki/Q124856) |
| **Adolphe Grison** | watercolorist, painter (1845-1914) | [Wikipedia](https://fr.wikipedia.org/wiki/Fran%C3%A7ois-Adolphe%20Grison) | [Q21888131](https://www.wikidata.org/wiki/Q21888131) |
| **Émile Bonnelat** | French politician (1845–1933) | [Wikipedia](https://fr.wikipedia.org/wiki/%C3%89mile%20Bonnelat) | [Q3588367](https://www.wikidata.org/wiki/Q3588367) |

## 1844

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1843

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1842

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Jean-Marie Clauzel** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/Jean-Marie%20Clauzel) | [Q16025459](https://www.wikidata.org/wiki/Q16025459) |

## 1841

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Karl Ivanovič Veber** | Russian diplomat (1841–1910) | [Wikipedia](https://fr.wikipedia.org/wiki/Karl%20Ivanovitch%20Weber) | [Q1041485](https://www.wikidata.org/wiki/Q1041485) |
| **Antonio Pacinotti** | Italian physicist (1841-1912) | [Wikipedia](https://fr.wikipedia.org/wiki/Antonio%20Pacinotti) | [Q460747](https://www.wikidata.org/wiki/Q460747) |

## 1840

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Alexander Frese** | Russian military leader | [Wikipedia](https://fr.wikipedia.org/wiki/Alexandre%20Frese) | [Q2833688](https://www.wikidata.org/wiki/Q2833688) |

## 1839

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **William Murray** | Canadian politician (1839-1898) | [Wikipedia](https://fr.wikipedia.org/wiki/William%20Murray%20(homme%20politique%20ontarien)) | [Q8015952](https://www.wikidata.org/wiki/Q8015952) |

## 1838

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Frederick Hollyer** | British photographer and graphic designer | [Wikipedia](https://fr.wikipedia.org/wiki/Frederick%20Hollyer) | [Q3496914](https://www.wikidata.org/wiki/Q3496914) |

## 1837

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Alexander Skene** | Scottish-American gynecologist (1837-1900) | [Wikipedia](https://fr.wikipedia.org/wiki/Alexander%20Skene%20(gyn%C3%A9cologue)) | [Q2734810](https://www.wikidata.org/wiki/Q2734810) |
| **Strong Vincent** | Union Army general (1837–1863) | [Wikipedia](https://fr.wikipedia.org/wiki/Strong%20Vincent) | [Q7624528](https://www.wikidata.org/wiki/Q7624528) |
| **Victor André Cornil** | French pathologist and politician (1837-1908) | [Wikipedia](https://fr.wikipedia.org/wiki/Victor%20Cornil) | [Q1388300](https://www.wikidata.org/wiki/Q1388300) |

## 1836

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Clas Theodor Odhner** | Swedish historian (1836–1904) | [Wikipedia](https://fr.wikipedia.org/wiki/Clas%20Theodor%20Odhner) | [Q731379](https://www.wikidata.org/wiki/Q731379) |
| **Gustave Masure** | French politician and journalist (1836-1886) | [Wikipedia](https://fr.wikipedia.org/wiki/Gustave%20Masure) | [Q8311630](https://www.wikidata.org/wiki/Q8311630) |

## 1835

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Émile Wróblewski** | Polish musician | [Wikipedia](https://fr.wikipedia.org/wiki/%C3%89mile%20Wr%C3%B3blewski) | [Q111164776](https://www.wikidata.org/wiki/Q111164776) |
| **Eugène Borel** | member of the Swiss Federal Council (1835-1892) | [Wikipedia](https://fr.wikipedia.org/wiki/Eug%C3%A8ne%20Borel) | [Q667709](https://www.wikidata.org/wiki/Q667709) |

## 1834

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Georg von Schleinitz** | German explorer (1834–1910) | [Wikipedia](https://fr.wikipedia.org/wiki/Georg%20von%20Schleinitz) | [Q117148](https://www.wikidata.org/wiki/Q117148) |
| **Kawaji Toshiyoshi** | Japanese politician | [Wikipedia](https://fr.wikipedia.org/wiki/Kawaji%20Toshiyoshi) | [Q3194335](https://www.wikidata.org/wiki/Q3194335) |
| **Gaston Nouël de Buzonnière** | French sculptor | [Wikipedia](https://fr.wikipedia.org/wiki/Gaston%20Nou%C3%ABl%20de%20Buzonni%C3%A8re) | [Q98633810](https://www.wikidata.org/wiki/Q98633810) |

## 1833

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Camille Soubise** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Camille%20Soubise) | [Q104634269](https://www.wikidata.org/wiki/Q104634269) |
| **Ferdinand Frensdorff** | German legal historian (1833–1931) | [Wikipedia](https://fr.wikipedia.org/wiki/Ferdinand%20Frensdorff) | [Q1405285](https://www.wikidata.org/wiki/Q1405285) |
| **Jules Tourgnol** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/Jules%20Tourgnol) | [Q16026565](https://www.wikidata.org/wiki/Q16026565) |
| **Francisco Manuel Oller** | Puerto Rican painter (1833 - 1917) | [Wikipedia](https://fr.wikipedia.org/wiki/Francisco%20Oller) | [Q2681959](https://www.wikidata.org/wiki/Q2681959) |

## 1832

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **George Herman Babcock** | American inventor (1832–1893) | [Wikipedia](https://fr.wikipedia.org/wiki/George%20Herman%20Babcock) | [Q1371083](https://www.wikidata.org/wiki/Q1371083) |
| **William Crookes** | British chemist and physicist (1832-1919) | [Wikipedia](https://fr.wikipedia.org/wiki/William%20Crookes) | [Q189552](https://www.wikidata.org/wiki/Q189552) |
| **Charles Baron Clarke** | British botanist (1832-1906) | [Wikipedia](https://fr.wikipedia.org/wiki/Charles%20Baron%20Clarke) | [Q2659116](https://www.wikidata.org/wiki/Q2659116) |

## 1831

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1830

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1829

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1828

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1827

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Albert Hermant** | Belgian politician and lawyer (1827-1883) | [Wikipedia](https://fr.wikipedia.org/wiki/Albert%20Hermant) | [Q16068892](https://www.wikidata.org/wiki/Q16068892) |
| **Giorgio Conrad** | Swiss Italian photographer (1827-1889) | [Wikipedia](https://fr.wikipedia.org/wiki/Giorgio%20Conrad) | [Q3106898](https://www.wikidata.org/wiki/Q3106898) |

## 1826

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **John P. C. Shanks** | U.S. Representative from Indiana (1826-1901) | [Wikipedia](https://fr.wikipedia.org/wiki/John%20P.%20C.%20Shanks) | [Q1701285](https://www.wikidata.org/wiki/Q1701285) |
| **Alfred James Hipkins** | English musicologist (1826-1903) | [Wikipedia](https://fr.wikipedia.org/wiki/Alfred%20Hipkins) | [Q2835181](https://www.wikidata.org/wiki/Q2835181) |

## 1825

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Elena Cuza** | Romanian noble and philanthropist | [Wikipedia](https://fr.wikipedia.org/wiki/Elena%20Rosetti) | [Q4975558](https://www.wikidata.org/wiki/Q4975558) |
| **Eugeniusz Adolf Lubomirski** | Polish art collector (1825-1911) | [Wikipedia](https://fr.wikipedia.org/wiki/Eugeniusz%20Adolf%20Lubomirski) | [Q9255980](https://www.wikidata.org/wiki/Q9255980) |

## 1824

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Arthur Wrottesley, 3rd Baron Wrottesley** | British politician and Baron (1824-1910) | [Wikipedia](https://fr.wikipedia.org/wiki/Arthur%20Wrottesley%20(3e%20baron%20Wrottesley)) | [Q16043598](https://www.wikidata.org/wiki/Q16043598) |
| **James McClatchy** | American newspaper editor (1824-1883) | [Wikipedia](https://fr.wikipedia.org/wiki/James%20McClatchy) | [Q1981100](https://www.wikidata.org/wiki/Q1981100) |
| **Ludovico Tuminello** | Italian photographer (1824-1907) | [Wikipedia](https://fr.wikipedia.org/wiki/Ludovico%20Tuminello) | [Q3266201](https://www.wikidata.org/wiki/Q3266201) |

## 1823

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Henri Faraud** | Catholic bishop (1823–1890) | [Wikipedia](https://fr.wikipedia.org/wiki/Henri%20Faraud) | [Q378769](https://www.wikidata.org/wiki/Q378769) |

## 1822

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Joseph A. Stargardt** | German bookseller | [Wikipedia](https://fr.wikipedia.org/wiki/Joseph%20A.%20Stargardt) | [Q1348464](https://www.wikidata.org/wiki/Q1348464) |
| **Charles Heidsieck** | French businessman and Champagne merchant | [Wikipedia](https://fr.wikipedia.org/wiki/Charles%20Heidsieck) | [Q2959334](https://www.wikidata.org/wiki/Q2959334) |
| **Enrico Delle Sedie** | Italian opera singer (1822–1907) | [Wikipedia](https://fr.wikipedia.org/wiki/Enrico%20delle%20Sedie) | [Q3725732](https://www.wikidata.org/wiki/Q3725732) |
| **Jules Joseph Boulanger** | Belgian painter (1822–1868) | [Wikipedia](https://fr.wikipedia.org/wiki/Jules%20Joseph%20Boulanger) | [Q21644886](https://www.wikidata.org/wiki/Q21644886) |

## 1821

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **John Henry Pepper** | British scientist and inventor (1821-1900) | [Wikipedia](https://fr.wikipedia.org/wiki/John%20Henry%20Pepper) | [Q6238921](https://www.wikidata.org/wiki/Q6238921) |
| **Ephraim George Squier** | American archaeologist and newspaper editor (1821–1888) | [Wikipedia](https://fr.wikipedia.org/wiki/Ephraim%20George%20Squier) | [Q721839](https://www.wikidata.org/wiki/Q721839) |

## 1820

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Émile Boniface** | French painter (1820-1895) | [Wikipedia](https://fr.wikipedia.org/wiki/%C3%89mile%20Boniface) | [Q21294581](https://www.wikidata.org/wiki/Q21294581) |
| **Eugène Froment-Delormel** | French, Painter, engraver, illustrator. Genre scenes, landscapes. (1820–1900) | [Wikipedia](https://fr.wikipedia.org/wiki/Eug%C3%A8ne%20Froment-Delormel) | [Q45299750](https://www.wikidata.org/wiki/Q45299750) |

## 1819

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Georges Wenner** | French organbuilder | [Wikipedia](https://fr.wikipedia.org/wiki/Georges%20Wenner) | [Q3103644](https://www.wikidata.org/wiki/Q3103644) |

## 1818

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Sophie of Württemberg** | Queen Consort of the Netherlands (1818–1877) | [Wikipedia](https://fr.wikipedia.org/wiki/Sophie%20de%20Wurtemberg) | [Q168674](https://www.wikidata.org/wiki/Q168674) |
| **Charles Gounod** | French composer (1818–1893) | [Wikipedia](https://fr.wikipedia.org/wiki/Charles%20Gounod) | [Q180278](https://www.wikidata.org/wiki/Q180278) |

## 1817

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Nikolaus Trübner** | German-English publisher and linguist, founder of Trübner & Co. | [Wikipedia](https://fr.wikipedia.org/wiki/Nicolas%20Tr%C3%BCbner) | [Q106821](https://www.wikidata.org/wiki/Q106821) |
| **Paul Cabaud** | (French, 1817–1895) | [Wikipedia](https://fr.wikipedia.org/wiki/Paul%20Cabaud) | [Q110176335](https://www.wikidata.org/wiki/Q110176335) |
| **Albéric Second** | French journalist and writer (1817–1887) | [Wikipedia](https://fr.wikipedia.org/wiki/Alb%C3%A9ric%20Second) | [Q1710530](https://www.wikidata.org/wiki/Q1710530) |
| **Théodore-Jacques Bonvalet** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Th%C3%A9odore-Jacques%20Bonvalet) | [Q20895239](https://www.wikidata.org/wiki/Q20895239) |
| **Louisy Mathieu** | Guadeloupean politician (1817-1874) | [Wikipedia](https://fr.wikipedia.org/wiki/Louisy%20Mathieu) | [Q3263912](https://www.wikidata.org/wiki/Q3263912) |
| **Hans Paludan Smith Schreuder** | Norwegian missionary working in South Africa (1817-1882) | [Wikipedia](https://fr.wikipedia.org/wiki/Hans%20Schreuder) | [Q4567452](https://www.wikidata.org/wiki/Q4567452) |

## 1816

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1815

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Louise Julien** | French poet and revolutionary | [Wikipedia](https://fr.wikipedia.org/wiki/Louise%20Julien) | [Q101472625](https://www.wikidata.org/wiki/Q101472625) |
| **Senior Sachs** | Jewish writer | [Wikipedia](https://fr.wikipedia.org/wiki/Senior%20Sachs) | [Q2903055](https://www.wikidata.org/wiki/Q2903055) |
| **Jean-Baptiste Houllet** | French botanist (1815-1890) | [Wikipedia](https://fr.wikipedia.org/wiki/Jean-Baptiste%20Houllet) | [Q3170553](https://www.wikidata.org/wiki/Q3170553) |

## 1814

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Jules-Jean-François Pérot** | French painter (1814-1876) | [Wikipedia](https://fr.wikipedia.org/wiki/Jules%20Jean%20Fran%C3%A7ois%20P%C3%A9rot) | [Q3188685](https://www.wikidata.org/wiki/Q3188685) |
| **Robert Grant** | Scottish astronomer (1814-1892) | [Wikipedia](https://fr.wikipedia.org/wiki/Robert%20Grant%20(astronome)) | [Q5768800](https://www.wikidata.org/wiki/Q5768800) |
| **Karl Hübner** | German artist (1814-1879) | [Wikipedia](https://fr.wikipedia.org/wiki/Carl%20Wilhelm%20H%C3%BCbner) | [Q876636](https://www.wikidata.org/wiki/Q876636) |

## 1813

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Xavier-Aloïse-Emmanuel-Léonce Hallez-Claparède** | French politician (1813-1870) | [Wikipedia](https://fr.wikipedia.org/wiki/L%C3%A9once%20Hallez-Clapar%C3%A8de) | [Q3271590](https://www.wikidata.org/wiki/Q3271590) |
| **Thomas Workman** | Canadian politician (1813–1889) | [Wikipedia](https://fr.wikipedia.org/wiki/Thomas%20Workman) | [Q3525677](https://www.wikidata.org/wiki/Q3525677) |
| **Thomas Maley Harris** | American general (1813–1906) | [Wikipedia](https://fr.wikipedia.org/wiki/Thomas%20Maley%20Harris) | [Q7792138](https://www.wikidata.org/wiki/Q7792138) |

## 1812

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Auguste Dutuit** | French art historian and collector (1812-1902) | [Wikipedia](https://fr.wikipedia.org/wiki/Auguste%20Dutuit) | [Q15983921](https://www.wikidata.org/wiki/Q15983921) |

## 1811

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Adolphe d'Ennery** | French Jewish dramatist and novelist (1811–1899) | [Wikipedia](https://fr.wikipedia.org/wiki/Adolphe%20d'Ennery) | [Q137819](https://www.wikidata.org/wiki/Q137819) |
| **Jón Sigurðsson** | leader of the 19th-century Icelandic independence movement (1811-1879) | [Wikipedia](https://fr.wikipedia.org/wiki/J%C3%B3n%20Sigur%C3%B0sson) | [Q321275](https://www.wikidata.org/wiki/Q321275) |
| **Pelegrí Clavé** | Catalan painter (1811-1880) | [Wikipedia](https://fr.wikipedia.org/wiki/Pelegr%C3%AD%20Clav%C3%A9) | [Q361959](https://www.wikidata.org/wiki/Q361959) |
| **Clarence Paget** | British sailor, politician and sculptor (1811-1895) | [Wikipedia](https://fr.wikipedia.org/wiki/Clarence%20Paget) | [Q6679084](https://www.wikidata.org/wiki/Q6679084) |

## 1810

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1809

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1808

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1807

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1806

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1805

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1804

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1803

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1802

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Hermann Goldschmidt** | German-French astronomer and painter (1802-1866) | [Wikipedia](https://fr.wikipedia.org/wiki/Hermann%20Mayer%20Salomon%20Goldschmidt) | [Q77022](https://www.wikidata.org/wiki/Q77022) |
| **Thomas Fraser, 12th Lord Lovat** | British noble (1802–1875) | [Wikipedia](https://fr.wikipedia.org/wiki/Thomas%20Fraser%20(12e%20lord%20Lovat)) | [Q7789797](https://www.wikidata.org/wiki/Q7789797) |

## 1801

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Jean Nicolas Houzeau-Muiron** | French politician (1801–1844) | [Wikipedia](https://fr.wikipedia.org/wiki/Jean%20Nicolas%20Houzeau-Muiron) | [Q3173705](https://www.wikidata.org/wiki/Q3173705) |

## 1800

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **William Parsons** | Anglo-Irish astronomer (1800-1867) | [Wikipedia](https://fr.wikipedia.org/wiki/William%20Parsons) | [Q310121](https://www.wikidata.org/wiki/Q310121) |

## 1799

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Pierre Thuillier** | French painter (1799-1858) | [Wikipedia](https://fr.wikipedia.org/wiki/Pierre%20Thuillier%20(peintre)) | [Q3387108](https://www.wikidata.org/wiki/Q3387108) |

## 1798

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1797

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Alexandre Vinet** | Swiss theologian and literary historian (1797-1847) | [Wikipedia](https://fr.wikipedia.org/wiki/Alexandre%20Vinet) | [Q124065](https://www.wikidata.org/wiki/Q124065) |

## 1796

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1795

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1794

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1793

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1792

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Charles-Pierre Bessières** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/Charles-Pierre%20Bessi%C3%A8res) | [Q2958286](https://www.wikidata.org/wiki/Q2958286) |
| **Jean-Alexandre Allais** | French engraver (1792–1850) | [Wikipedia](https://fr.wikipedia.org/wiki/Jean-Alexandre%20Allais) | [Q3163668](https://www.wikidata.org/wiki/Q3163668) |

## 1791

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Irénée François David** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/Ir%C3%A9n%C3%A9e%20Fran%C3%A7ois%20David) | [Q16026689](https://www.wikidata.org/wiki/Q16026689) |
| **Roberto Cofresí** | Puerto Rican pirate (1791–1825) | [Wikipedia](https://fr.wikipedia.org/wiki/Roberto%20Cofres%C3%AD) | [Q2341815](https://www.wikidata.org/wiki/Q2341815) |

## 1790

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Guillaume Angebault** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Guillaume%20Angebault) | [Q3119643](https://www.wikidata.org/wiki/Q3119643) |
| **Abel P. Upshur** | lawyer and politician (1790-1844) | [Wikipedia](https://fr.wikipedia.org/wiki/Abel%20P.%20Upshur) | [Q318482](https://www.wikidata.org/wiki/Q318482) |

## 1789

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Antoine-Geneviève-Héraclius-Agénor de Gramont** | French general (1789-1855) | [Wikipedia](https://fr.wikipedia.org/wiki/H%C3%A9raclius%20de%20Gramont) | [Q165581](https://www.wikidata.org/wiki/Q165581) |

## 1788

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1787

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Princess Charlotte of Saxe-Hildburghausen** | German princess (1787-1847) | [Wikipedia](https://fr.wikipedia.org/wiki/Charlotte%20de%20Saxe-Hildburghausen) | [Q64462](https://www.wikidata.org/wiki/Q64462) |
| **William Rathbone** | English merchant and politician | [Wikipedia](https://fr.wikipedia.org/wiki/William%20Rathbone%20V) | [Q8017387](https://www.wikidata.org/wiki/Q8017387) |

## 1786

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Charles Vernes** | banker (1786-1858) | [Wikipedia](https://fr.wikipedia.org/wiki/Charles%20Vernes) | [Q16194908](https://www.wikidata.org/wiki/Q16194908) |

## 1785

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Charles Ashe à Court-Repington** | British Army officer and politician | [Wikipedia](https://fr.wikipedia.org/wiki/Charles%20Ashe%20%C3%A0%20Court-Repington) | [Q19502096](https://www.wikidata.org/wiki/Q19502096) |

## 1784

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Aleksei Ivanovitch Bartolomei** | Russian military personnel of Baltic German origin (1784-1839) | [Wikipedia](https://fr.wikipedia.org/wiki/Alexe%C3%AF%20Ivanovitch%20Bartolomei) | [Q2834349](https://www.wikidata.org/wiki/Q2834349) |
| **Frederick Adam** | British Army general (1781 or 1784-1781) | [Wikipedia](https://fr.wikipedia.org/wiki/Frederick%20Adam) | [Q320992](https://www.wikidata.org/wiki/Q320992) |
| **Friedrich Thiersch** | German classical scholar (1784-1860) | [Wikipedia](https://fr.wikipedia.org/wiki/Friedrich%20Thiersch) | [Q73076](https://www.wikidata.org/wiki/Q73076) |

## 1783

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Adrien François Lemaistre** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/Adrien%20Fran%C3%A7ois%20Lemaistre) | [Q15969208](https://www.wikidata.org/wiki/Q15969208) |
| **Pierre-Marie Touboulic** | French engineer, inventor and writer | [Wikipedia](https://fr.wikipedia.org/wiki/Pierre-Marie%20Touboulic) | [Q3383368](https://www.wikidata.org/wiki/Q3383368) |

## 1782

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1781

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Francisco Espoz y Mina** | Spanish military commander | [Wikipedia](https://fr.wikipedia.org/wiki/Francisco%20Espoz%20y%20Mina) | [Q2745347](https://www.wikidata.org/wiki/Q2745347) |

## 1780

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Auguste Guenepin** | French architect | [Wikipedia](https://fr.wikipedia.org/wiki/Auguste%20Guenepin) | [Q2871216](https://www.wikidata.org/wiki/Q2871216) |
| **Jacob Joseph Oettinger** | Jewish theologian | [Wikipedia](https://fr.wikipedia.org/wiki/Jacob%20Joseph%20Oettinger) | [Q19518655](https://www.wikidata.org/wiki/Q19518655) |

## 1779

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Eugène Hyacinthe Laffillard** | French playwright | [Wikipedia](https://fr.wikipedia.org/wiki/Eug%C3%A8ne%20Hyacinthe%20Laffillard) | [Q19629459](https://www.wikidata.org/wiki/Q19629459) |

## 1778

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Iphigénie Decaux-Milet-Moreau** | French painter | [Wikipedia](https://fr.wikipedia.org/wiki/Iphig%C3%A9nie%20Milet-Mureau) | [Q18535073](https://www.wikidata.org/wiki/Q18535073) |
| **Pierre-Ange Vieillard** | French librarian and librettist (1778-1862) | [Wikipedia](https://fr.wikipedia.org/wiki/Pierre-Ange%20Vieillard) | [Q3382831](https://www.wikidata.org/wiki/Q3382831) |
| **Gregory Blaxland** | English explorer and pastoralist in New South Wales, Australia (1778-1853) | [Wikipedia](https://fr.wikipedia.org/wiki/Gregory%20Blaxland) | [Q962593](https://www.wikidata.org/wiki/Q962593) |

## 1777

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1776

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Jean-Baptiste Joachim Clémot** | French politician | [Wikipedia](https://fr.wikipedia.org/wiki/Jean-Baptiste%20Cl%C3%A9mot) | [Q25925545](https://www.wikidata.org/wiki/Q25925545) |
| **Alexandre Charles Joseph Ghislain d'Aubremé** | Belgian politician | [Wikipedia](https://fr.wikipedia.org/wiki/Alexandre%20d'Aubrem%C3%A9) | [Q2834157](https://www.wikidata.org/wiki/Q2834157) |
| **René Jacques Henri Delaporte** | French military personnel (1776–1848) | [Wikipedia](https://fr.wikipedia.org/wiki/Ren%C3%A9%20Jacques%20Henri%20Delaporte) | [Q3426389](https://www.wikidata.org/wiki/Q3426389) |

## 1775

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1774

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1773

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1772

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1771

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1770

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1769

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1768

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1767

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1766

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1765

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1764

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1763

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1762

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1761

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1760

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1759

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1758

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1757

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1756

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1755

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1754

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1753

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1752

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1751

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1750

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1749

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1748

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1747

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1746

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1745

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1744

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1743

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1742

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1741

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1740

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1739

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Ermenegildo Pini** | Italian mathematician, naturalist and architect (1739-1825) | [Wikipedia](https://fr.wikipedia.org/wiki/Ermenegildo%20Pini) | [Q16658104](https://www.wikidata.org/wiki/Q16658104) |

## 1738

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1737

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Jacques Belhomme** | French pension owner (1737-1824) | [Wikipedia](https://fr.wikipedia.org/wiki/Jacques%20Belhomme) | [Q3158231](https://www.wikidata.org/wiki/Q3158231) |

## 1736

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1735

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1734

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1733

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Sir Richard Hill, 2nd Baronet** | Tory Member of Parliament for Shropshire, 1780-1806 | [Wikipedia](https://fr.wikipedia.org/wiki/Richard%20Hill%20(2e%20baronnet)) | [Q7528603](https://www.wikidata.org/wiki/Q7528603) |

## 1732

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1731

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1730

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1729

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1728

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1727

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Théophile Rémy Frêne** | Swiss pastor (1727-1804) | [Wikipedia](https://fr.wikipedia.org/wiki/Th%C3%A9ophile%20R%C3%A9my%20Fr%C3%AAne) | [Q119860](https://www.wikidata.org/wiki/Q119860) |

## 1726

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1725

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1724

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1723

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Johann Baptist Wendling** | German composer | [Wikipedia](https://fr.wikipedia.org/wiki/Johann%20Baptist%20Wendling) | [Q214928](https://www.wikidata.org/wiki/Q214928) |
| **Friedrich Boerner** | physician | [Wikipedia](https://fr.wikipedia.org/wiki/Friedrich%20Boerner) | [Q84498](https://www.wikidata.org/wiki/Q84498) |

## 1722

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1721

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1720

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1719

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1718

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **George Howard** | British field marshal and politician | [Wikipedia](https://fr.wikipedia.org/wiki/George%20Howard%20(mar%C3%A9chal)) | [Q4140861](https://www.wikidata.org/wiki/Q4140861) |

## 1717

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1716

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1715

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Théodore Baron d'Hénouville** | French physician | [Wikipedia](https://fr.wikipedia.org/wiki/Th%C3%A9odore%20Baron%20d'H%C3%A9nouville) | [Q22582882](https://www.wikidata.org/wiki/Q22582882) |
| **Jean Baptiste Requier** | French scientist | [Wikipedia](https://fr.wikipedia.org/wiki/Jean-Baptiste%20Requier) | [Q56006945](https://www.wikidata.org/wiki/Q56006945) |

## 1714

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1713

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1712

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1711

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1710

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1709

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1708

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1707

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1706

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1705

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1704

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1703

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1702

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1701

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1700

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1699

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1698

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1697

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Thomas Coke, 1st Earl of Leicester** | British landowner (1697-1759) | [Wikipedia](https://fr.wikipedia.org/wiki/Thomas%20Coke%20(1er%20comte%20de%20Leicester%2C%201697-1759)) | [Q337655](https://www.wikidata.org/wiki/Q337655) |

## 1696

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1695

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Henri-Michel Guedier de Saint-Aubin** | French theologist (1695-1741) | [Wikipedia](https://fr.wikipedia.org/wiki/Henri-Michel%20Guedier%20de%20Saint-Aubin) | [Q18736524](https://www.wikidata.org/wiki/Q18736524) |

## 1694

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1693

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Prince Karl Wilhelm of Hesse-Darmstadt** | Prince of Hesse-Darmstadt and Obrist | [Wikipedia](https://fr.wikipedia.org/wiki/Charles-Guillaume%20de%20Hesse-Darmstadt) | [Q145200](https://www.wikidata.org/wiki/Q145200) |
| **Johann Georg Walch** | German theologian (1693-1775) | [Wikipedia](https://fr.wikipedia.org/wiki/Johann%20Georg%20Walch) | [Q70352](https://www.wikidata.org/wiki/Q70352) |

## 1692

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1691

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Georg August zu Erbach-Schönberg** | German noble | [Wikipedia](https://fr.wikipedia.org/wiki/Georges-Auguste%20d'Erbach-Sch%C3%B6nberg) | [Q11928274](https://www.wikidata.org/wiki/Q11928274) |
| **Giovanni Paolo Panini** | Italian painter and architect (1691–1765) | [Wikipedia](https://fr.wikipedia.org/wiki/Giovanni%20Paolo%20Panini) | [Q286670](https://www.wikidata.org/wiki/Q286670) |

## 1690

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1689

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1688

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1687

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1686

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1685

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1684

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1683

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1682

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1681

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1680

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1679

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1678

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1677

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1676

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1675

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1674

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1673

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1672

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Charlotte of Hesse-Homburg** | German noble (1672–1738) | [Wikipedia](https://fr.wikipedia.org/wiki/Charlotte-Doroth%C3%A9e-Sophie%20de%20Hesse-Hombourg) | [Q328606](https://www.wikidata.org/wiki/Q328606) |

## 1671

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1670

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1669

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1668

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1667

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1666

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1665

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1664

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1663

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1662

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1661

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1660

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1659

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1658

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1657

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1656

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1655

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1654

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1653

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1652

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1651

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1650

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1649

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1648

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1647

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1646

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1645

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1644

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1643

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1642

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1641

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1640

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1639

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1638

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1637

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1636

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1635

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1634

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1633

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1632

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1631

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1630

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1629

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1628

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1627

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1626

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1625

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Peder Hansen Resen** | Danish historian | [Wikipedia](https://fr.wikipedia.org/wiki/Peder%20Hansen%20Resen) | [Q426776](https://www.wikidata.org/wiki/Q426776) |

## 1624

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1623

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1622

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1621

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1620

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1619

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1618

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1617

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1616

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Georg Ludwig von Sinzendorff** | Austrian politician and statesperson (1616-1681) | [Wikipedia](https://fr.wikipedia.org/wiki/Georg%20Ludwig%20von%20Sinzendorf) | [Q1505273](https://www.wikidata.org/wiki/Q1505273) |
| **Jerzy Sebastian Lubomirski** | Polish noble (1616-1667) | [Wikipedia](https://fr.wikipedia.org/wiki/Jerzy%20Sebastian%20Lubomirski) | [Q269774](https://www.wikidata.org/wiki/Q269774) |

## 1615

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1614

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1613

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Amedeo di Castellamonte** | Italian architect (1613-1683) | [Wikipedia](https://fr.wikipedia.org/wiki/Amedeo%20di%20Castellamonte) | [Q3613931](https://www.wikidata.org/wiki/Q3613931) |

## 1612

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1611

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Hoshina Masayuki** | daimyo of the early Edo period; 1st lord of Aizu | [Wikipedia](https://fr.wikipedia.org/wiki/Hoshina%20Masayuki) | [Q837236](https://www.wikidata.org/wiki/Q837236) |

## 1610

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Brigitte Morello** | religious Italian, founder of the Ursuline Sisters of Mary Immaculate | [Wikipedia](https://fr.wikipedia.org/wiki/Brigitte%20Morello) | [Q3644748](https://www.wikidata.org/wiki/Q3644748) |
| **Birgitte Thott** | Danish philosopher, auther, and scholar (1610-1662) | [Wikipedia](https://fr.wikipedia.org/wiki/Birgitte%20Thott) | [Q4916320](https://www.wikidata.org/wiki/Q4916320) |

## 1609

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1608

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1607

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1606

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1605

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1604

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1603

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1602

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1601

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1600

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1599

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1598

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1597

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1596

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1595

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1594

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1593

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1592

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1591

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1590

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1589

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1588

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1587

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1586

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1585

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1584

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Thalun** | Eighth king of Toungoo dynasty of Burma | [Wikipedia](https://fr.wikipedia.org/wiki/Thalun) | [Q3056645](https://www.wikidata.org/wiki/Q3056645) |

## 1583

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1582

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1581

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1580

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1579

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1578

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1577

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1576

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1575

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1574

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1573

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1572

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1571

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Thomas Mun** | English economist (1571–1641) | [Wikipedia](https://fr.wikipedia.org/wiki/Thomas%20Mun) | [Q505697](https://www.wikidata.org/wiki/Q505697) |

## 1570

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1569

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1568

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1567

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1566

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1565

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1564

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1563

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1562

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1561

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **John VII, Count of Nassau-Siegen** | Count of Nassau-Siegen (1606-1623) | [Wikipedia](https://fr.wikipedia.org/wiki/Jean%20VII%20de%20Nassau-Siegen) | [Q819521](https://www.wikidata.org/wiki/Q819521) |

## 1560

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1559

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1558

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1557

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1556

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1555

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1554

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1553

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|

## 1552

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **John George of Ohlau** | Duke of Oława and Wołów | [Wikipedia](https://fr.wikipedia.org/wiki/Jean-Georges%20d'O%C5%82awa) | [Q325932](https://www.wikidata.org/wiki/Q325932) |

## 1971

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Paulina Rubio** | Mexican singer (born 1971) | [Wikipedia](https://fr.wikipedia.org/wiki/Paulina%20Rubio) | [Q202536](https://www.wikidata.org/wiki/Q202536) |
| **Hans-Peter Obwaller** | Austrian bicycle racer | [Wikipedia](https://fr.wikipedia.org/wiki/Hans-Peter%20Obwaller) | [Q269627](https://www.wikidata.org/wiki/Q269627) |
| **Hervé Yamguen** | artist from Cameroon | [Wikipedia](https://fr.wikipedia.org/wiki/Herv%C3%A9%20Yamguen) | [Q425784](https://www.wikidata.org/wiki/Q425784) |
| **Bif Naked** | Canadian singer | [Wikipedia](https://fr.wikipedia.org/wiki/Bif%20Naked) | [Q451278](https://www.wikidata.org/wiki/Q451278) |
| **José Emilio Amavisca** | Spanish footballer | [Wikipedia](https://fr.wikipedia.org/wiki/Jos%C3%A9%20Amavisca) | [Q456326](https://www.wikidata.org/wiki/Q456326) |
| **Tripp Schwenk** | American swimmer | [Wikipedia](https://fr.wikipedia.org/wiki/Tripp%20Schwenk) | [Q1134029](https://www.wikidata.org/wiki/Q1134029) |
| **Reto Nause** | Swiss politician | [Wikipedia](https://fr.wikipedia.org/wiki/Reto%20Nause) | [Q1497859](https://www.wikidata.org/wiki/Q1497859) |
| **Helen Clayton** | English rugby union player | [Wikipedia](https://fr.wikipedia.org/wiki/Helen%20Clayton) | [Q3129602](https://www.wikidata.org/wiki/Q3129602) |
| **Nicolas Vadot** | French comics author | [Wikipedia](https://fr.wikipedia.org/wiki/Nicolas%20Vadot) | [Q3340830](https://www.wikidata.org/wiki/Q3340830) |
| **Espen Sandberg** | Norwegian film director and advertising executive | [Wikipedia](https://fr.wikipedia.org/wiki/Espen%20Sandberg) | [Q3368851](https://www.wikidata.org/wiki/Q3368851) |
| **Yelena Melnikova** | Olympic medalist in biathlon | [Wikipedia](https://fr.wikipedia.org/wiki/Elena%20Melnikova) | [Q525611](https://www.wikidata.org/wiki/Q525611) |
| **Emmanuel Moreno** | Israeli Army officer | [Wikipedia](https://fr.wikipedia.org/wiki/Emmanuel%20Yehouda%20Moreno) | [Q5373297](https://www.wikidata.org/wiki/Q5373297) |
| **Johan Danen** | Flemish politician | [Wikipedia](https://fr.wikipedia.org/wiki/Johan%20Danen) | [Q17350524](https://www.wikidata.org/wiki/Q17350524) |
| **Fortunato Cerlino** | Italian actor | [Wikipedia](https://fr.wikipedia.org/wiki/Fortunato%20Cerlino) | [Q18202739](https://www.wikidata.org/wiki/Q18202739) |
| **Jorien van Nes** | Dutch film director | [Wikipedia](https://fr.wikipedia.org/wiki/Jorien%20van%20Nes) | [Q59012935](https://www.wikidata.org/wiki/Q59012935) |
| **Irene Lozano** | Spanish writer and journalist | [Wikipedia](https://fr.wikipedia.org/wiki/Irene%20Lozano) | [Q5920188](https://www.wikidata.org/wiki/Q5920188) |

## 1973

| Nom | Description | Wikipedia | Wikidata |
|-----|-------------|-----------|----------|
| **Aurélie Filippetti** | French politician and writer | [Wikipedia](https://fr.wikipedia.org/wiki/Aur%C3%A9lie%20Filippetti) | [Q198005](https://www.wikidata.org/wiki/Q198005) |
| **Leander Paes** | Indian tennis player | [Wikipedia](https://fr.wikipedia.org/wiki/Leander%20Paes) | [Q296282](https://www.wikidata.org/wiki/Q296282) |
| **Louis Leterrier** | French film director | [Wikipedia](https://fr.wikipedia.org/wiki/Louis%20Leterrier) | [Q525332](https://www.wikidata.org/wiki/Q525332) |
| **Toshimi Kikuchi** | Japanese association football player and manager | [Wikipedia](https://fr.wikipedia.org/wiki/Toshimi%20Kikuchi) | [Q1185459](https://www.wikidata.org/wiki/Q1185459) |
| **Tommy Ho** | US tennis player | [Wikipedia](https://fr.wikipedia.org/wiki/Tommy%20Ho) | [Q1337412](https://www.wikidata.org/wiki/Q1337412) |
| **Helge Burggrabe** | German composer, recorder player and scenographer | [Wikipedia](https://fr.wikipedia.org/wiki/Helge%20Burggrabe) | [Q1434908](https://www.wikidata.org/wiki/Q1434908) |
| **Oliver Gross** | German tennis player | [Wikipedia](https://fr.wikipedia.org/wiki/Oliver%20Gross) | [Q2020241](https://www.wikidata.org/wiki/Q2020241) |
| **Andrey Kozyrev** | Russian hockey player and sports coach | [Wikipedia](https://fr.wikipedia.org/wiki/Andre%C3%AF%20Kozyrev%20(hockey%20sur%20glace)) | [Q2846816](https://www.wikidata.org/wiki/Q2846816) |
| **Henri Sagna** | Senegalese sculptor | [Wikipedia](https://fr.wikipedia.org/wiki/Henri%20Sagna) | [Q3131970](https://www.wikidata.org/wiki/Q3131970) |
| **Krayzie Bone** | American rapper | [Wikipedia](https://fr.wikipedia.org/wiki/Krayzie%20Bone) | [Q529555](https://www.wikidata.org/wiki/Q529555) |
| **Matthieu Bonhomme** | French comics artist | [Wikipedia](https://fr.wikipedia.org/wiki/Matthieu%20Bonhomme) | [Q3299866](https://www.wikidata.org/wiki/Q3299866) |
| **Óscar Lagos** | Honduran association football player | [Wikipedia](https://fr.wikipedia.org/wiki/%C3%93scar%20Lagos) | [Q3886425](https://www.wikidata.org/wiki/Q3886425) |
| **Larysa Denysenko** | Ukrainian journalist and lawyer | [Wikipedia](https://fr.wikipedia.org/wiki/Larysa%20Denysenko) | [Q4157921](https://www.wikidata.org/wiki/Q4157921) |
| **Mark Umbers** | British actor | [Wikipedia](https://fr.wikipedia.org/wiki/Mark%20Umbers) | [Q6770110](https://www.wikidata.org/wiki/Q6770110) |
| **Nahnatchka Khan** | American television producer and writer | [Wikipedia](https://fr.wikipedia.org/wiki/Nahnatchka%20Khan) | [Q6959303](https://www.wikidata.org/wiki/Q6959303) |
| **Melaaz Benacer** | Algerian rapper | [Wikipedia](https://fr.wikipedia.org/wiki/Melaaz) | [Q105825020](https://www.wikidata.org/wiki/Q105825020) |
| **Arnaud Noury** | French archaeologist | [Wikipedia](https://fr.wikipedia.org/wiki/Arnaud%20Noury) | [Q23017381](https://www.wikidata.org/wiki/Q23017381) |
| **Louise Meintjies** | South African athletics competitor | [Wikipedia](https://fr.wikipedia.org/wiki/Louise%20Meintjies) | [Q24951639](https://www.wikidata.org/wiki/Q24951639) |
| **Yakov Rezantsev** | Russian general (born 1973) | [Wikipedia](https://fr.wikipedia.org/wiki/Iakov%20Rezantsev) | [Q62713990](https://www.wikidata.org/wiki/Q62713990) |
| **Q138856089** |  | [Wikipedia](https://fr.wikipedia.org/wiki/Atafa%C3%AF%20Tchangani) | [Q138856089](https://www.wikidata.org/wiki/Q138856089) |

